export const GRID_COLS = 30;
export const GRID_ROWS = 20;
export const CELL_SIZE = 36;

// ─── TOWER UPGRADES ───────────────────────────────────────────────────────────
export const TOWER_UPGRADES = {
  basic: {
    passives: [
      { tier: 1, xp: 20, stat: "damage", mult: 0.12, label: "+12% dmg" },
      { tier: 2, xp: 40, stat: "range", mult: 0.08, label: "+8% range" },
      { tier: 3, xp: 80, stat: "damage", mult: 0.18, label: "+18% dmg" },
      {
        tier: 4,
        xp: 140,
        stat: "fireRate",
        mult: -0.1,
        label: "−10% cooldown",
      },
      // tier 5 = skill5 gate
      { tier: 6, xp: 220, stat: "damage", mult: 0.22, label: "+22% dmg" },
      { tier: 7, xp: 260, stat: "range", mult: 0.12, label: "+12% range" },
      { tier: 8, xp: 400, stat: "damage", mult: 0.28, label: "+28% dmg" },
      {
        tier: 9,
        xp: 480,
        stat: "fireRate",
        mult: -0.15,
        label: "−15% cooldown",
      },
    ],
    skill5: {
      xp: 170,
      A: {
        name: "Marksman",
        desc: "+50% dmg, +15% range",
        icon: "🎯",
        cost: 60,
        statDelta: { damage: 0.5, range: 0.15 },
      },
      B: {
        name: "Gatling",
        desc: "2× fire rate",
        icon: "🌀",
        cost: 60,
        statDelta: { fireRate: -0.5 },
      },
    },
    skill10: {
      xp: 620,
      A: {
        name: "Deadeye",
        desc: "+100% dmg, armor pierce",
        icon: "💥",
        cost: 100,
        statDelta: { damage: 1.0 },
        special: "armorPiercing",
      },
      B: {
        name: "Assault",
        desc: "3× fire rate + splash",
        icon: "⚡",
        cost: 100,
        statDelta: { fireRate: -0.66 },
        special: "splash30",
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Overwatch",
        desc: "Bullets chain to nearest enemy on hit.",
        icon: "🔱",
        cost: 400,
        special: "bulletChain",
      },
      B: {
        name: "Siege Mode",
        desc: "+200% dmg, −50% fire rate. Armor pierce.",
        icon: "🏰",
        cost: 400,
        statDelta: { damage: 2.0, fireRate: 0.5 },
        special: "armorPiercing",
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Singularity",
        desc: "Every 10th bullet creates a black hole.",
        icon: "🌌",
        cost: 800,
        special: "blackHole",
      },
      B: {
        name: "God Mode",
        desc: "+300% dmg, infinite range, full pierce.",
        icon: "⚡",
        cost: 800,
        statDelta: { damage: 1.5, range: 1.25 },
        special: "fullPierce",
      },
    },
    // ── WAVE 200 ASCENSION ────────────────────────────────────────────────────
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Extinction Protocol",
        desc: "Every bullet applies 3 stacks of every debuff simultaneously.",
        icon: "☄️",
        cost: 2000,
        special: "extinctionProtocol",
      },
      B: {
        name: "Void Arsenal",
        desc: "+500% dmg. Shots create expanding void rings.",
        icon: "🌀",
        cost: 2000,
        statDelta: { damage: 5.0 },
        special: "voidRings",
      },
    },
  },

  sniper: {
    passives: [
      { tier: 1, xp: 20, stat: "damage", mult: 0.15, label: "+15% dmg" },
      { tier: 2, xp: 25, stat: "range", mult: 0.12, label: "+12% range" },
      { tier: 3, xp: 60, stat: "damage", mult: 0.2, label: "+20% dmg" },
      {
        tier: 4,
        xp: 110,
        stat: "fireRate",
        mult: -0.1,
        label: "−10% cooldown",
      },
      { tier: 6, xp: 240, stat: "damage", mult: 0.28, label: "+28% dmg" },
      { tier: 7, xp: 340, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 8, xp: 430, stat: "damage", mult: 0.35, label: "+35% dmg" },
      {
        tier: 9,
        xp: 480,
        stat: "fireRate",
        mult: -0.12,
        label: "−12% cooldown",
      },
    ],
    skill5: {
      xp: 140,
      A: {
        name: "Longshot",
        desc: "+40% range, +30% dmg",
        icon: "🔭",
        cost: 90,
        statDelta: { range: 0.4, damage: 0.3 },
      },
      B: {
        name: "Piercer",
        desc: "Armor pierce + 20% dmg",
        icon: "🗡️",
        cost: 90,
        statDelta: { damage: 0.2 },
        special: "armorPiercing",
      },
    },
    skill10: {
      xp: 530,
      A: {
        name: "Rail Gun",
        desc: "+150% dmg, pass-through",
        icon: "☄️",
        cost: 150,
        statDelta: { damage: 1.5 },
        special: "pierceThrough",
      },
      B: {
        name: "Hemorrhage",
        desc: "Shots apply anti-heal — target cannot regenerate for 6s",
        icon: "🩸",
        cost: 150,
        statDelta: { damage: 0.4 },
        special: "antiHeal",
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "God's Eye",
        desc: "Reveals all stealth. Crits ignore armor.",
        icon: "👁️",
        cost: 400,
        special: "allReveal",
      },
      B: {
        name: "Twin Barrels",
        desc: "Fires 2 shots simultaneously.",
        icon: "⚔️",
        cost: 400,
        special: "twinShot",
        statDelta: { damage: 0.5 },
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Antimatter",
        desc: "Shots trigger a delayed void explosion.",
        icon: "💫",
        cost: 800,
        special: "voidBurst",
      },
      B: {
        name: "Time Stop",
        desc: "Every 5th shot freezes all enemies 2s.",
        icon: "⏱️",
        cost: 800,
        special: "timeStop",
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "One Shot One Kill",
        desc: "Every shot instantly kills enemies below 40% HP. Bosses take 4× dmg.",
        icon: "💀",
        cost: 2000,
        special: "executionShot",
      },
      B: {
        name: "Omniscience",
        desc: "Infinite range. Hits all enemies on the map simultaneously every 5s.",
        icon: "🌐",
        cost: 2000,
        special: "omniscience",
      },
    },
  },

  cannon: {
    passives: [
      { tier: 1, xp: 24, stat: "damage", mult: 0.12, label: "+12% dmg" },
      { tier: 2, xp: 48, stat: "splash", mult: 0.1, label: "+10% splash" },
      { tier: 3, xp: 95, stat: "damage", mult: 0.18, label: "+18% dmg" },
      {
        tier: 4,
        xp: 145,
        stat: "fireRate",
        mult: -0.1,
        label: "−10% cooldown",
      },
      { tier: 6, xp: 250, stat: "damage", mult: 0.22, label: "+22% dmg" },
      { tier: 7, xp: 335, stat: "splash", mult: 0.2, label: "+20% splash" },
      { tier: 8, xp: 440, stat: "damage", mult: 0.3, label: "+30% dmg" },
      {
        tier: 9,
        xp: 520,
        stat: "fireRate",
        mult: -0.15,
        label: "−15% cooldown",
      },
    ],
    skill5: {
      xp: 185,
      A: {
        name: "Bombard",
        desc: "+60% splash radius",
        icon: "💣",
        cost: 80,
        statDelta: { splash: 0.6 },
      },
      B: {
        name: "Velocity",
        desc: "+50% proj speed, −20% cd",
        icon: "🚀",
        cost: 80,
        statDelta: { projectileSpeed: 0.5, fireRate: -0.2 },
      },
    },
    skill10: {
      xp: 620,
      A: {
        name: "Napalm",
        desc: "Splash leaves burning ground",
        icon: "🔥",
        cost: 130,
        statDelta: { splash: 0.3 },
        special: "burnOnSplash",
      },
      B: {
        name: "Cluster",
        desc: "Splits into 3 mini-shots",
        icon: "🌟",
        cost: 130,
        statDelta: { damage: 0.5 },
        special: "clusterShot",
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Earthquake",
        desc: "Every shot stuns nearby enemies 0.5s.",
        icon: "🌋",
        cost: 400,
        special: "quakeStun",
      },
      B: {
        name: "Bunker Buster",
        desc: "+150% dmg vs bosses, armor pierce.",
        icon: "💥",
        cost: 400,
        special: "armorPiercing",
        statDelta: { damage: 0.5 },
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Nuke",
        desc: "Every 8th shot = full-screen nuke.",
        icon: "☢️",
        cost: 800,
        special: "nuke",
      },
      B: {
        name: "Meteor Storm",
        desc: "Continuous rain of small blasts.",
        icon: "🌠",
        cost: 800,
        special: "meteorStorm",
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Planet Cracker",
        desc: "Every 3rd shot = screen nuke + leaves permanent burn zone.",
        icon: "🌍",
        cost: 2000,
        special: "planetCracker",
      },
      B: {
        name: "Tectonic",
        desc: "+300% splash radius. Pulls all enemies toward impact point.",
        icon: "🌋",
        cost: 2000,
        statDelta: { splash: 3.0 },
        special: "tectonicPull",
      },
    },
  },

  laser: {
    passives: [
      { tier: 1, xp: 24, stat: "damage", mult: 0.12, label: "+12% dmg" },
      { tier: 2, xp: 52, stat: "range", mult: 0.1, label: "+10% range" },
      { tier: 3, xp: 95, stat: "damage", mult: 0.18, label: "+18% dmg" },
      {
        tier: 4,
        xp: 150,
        stat: "fireRate",
        mult: -0.12,
        label: "−12% cooldown",
      },
      { tier: 6, xp: 280, stat: "damage", mult: 0.25, label: "+25% dmg" },
      { tier: 7, xp: 385, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 8, xp: 495, stat: "damage", mult: 0.32, label: "+32% dmg" },
      {
        tier: 9,
        xp: 625,
        stat: "fireRate",
        mult: -0.15,
        label: "−15% cooldown",
      },
    ],
    skill5: {
      xp: 185,
      A: {
        name: "Overclock",
        desc: "2× fire rate, +20% dmg",
        icon: "⚡",
        cost: 100,
        statDelta: { fireRate: -0.5, damage: 0.2 },
      },
      B: {
        name: "Lens",
        desc: "+50% range, +30% dmg",
        icon: "🔬",
        cost: 100,
        statDelta: { range: 0.5, damage: 0.3 },
      },
    },
    skill10: {
      xp: 760,
      A: {
        name: "Death Ray",
        desc: "Hits ALL enemies in range",
        icon: "🌈",
        cost: 180,
        statDelta: { damage: 0.25 },
        special: "beamAll",
      },
      B: {
        name: "Disruptor",
        desc: "Slows + stuns 0.5s on hit",
        icon: "🌀",
        cost: 180,
        statDelta: { damage: 0.3 },
        special: "stunOnHit",
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Solar Flare",
        desc: "Every 10th shot blinds all enemies 2s.",
        icon: "☀️",
        cost: 400,
        special: "solarBlind",
      },
      B: {
        name: "Prism",
        desc: "Beam splits and hits 3 targets.",
        icon: "🔷",
        cost: 400,
        special: "prismSplit",
        statDelta: { damage: 0.4 },
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Omega Ray",
        desc: "Continuous beam hits entire path.",
        icon: "🔆",
        cost: 800,
        special: "omegaBeam",
      },
      B: {
        name: "Void Laser",
        desc: "Ignores all immunities. True dmg.",
        icon: "🌑",
        cost: 800,
        special: "trueDamage",
        statDelta: { damage: 1.0 },
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Solar God",
        desc: "Permanent beam hits every enemy on screen every tick. True damage.",
        icon: "☀️",
        cost: 2000,
        special: "solarGod",
      },
      B: {
        name: "Mirror Web",
        desc: "Each beam reflects off enemies hitting up to 8 additional targets.",
        icon: "🕸️",
        cost: 2000,
        statDelta: { damage: 0.8 },
        special: "mirrorWeb",
      },
    },
  },

  freeze: {
    passives: [
      {
        tier: 1,
        xp: 15,
        stat: "slowDuration",
        mult: 0.12,
        label: "+12% slow dur",
      },
      { tier: 2, xp: 30, stat: "damage", mult: 0.1, label: "+10% dmg" },
      {
        tier: 3,
        xp: 58,
        stat: "slowDuration",
        mult: 0.18,
        label: "+18% slow dur",
      },
      { tier: 4, xp: 105, stat: "range", mult: 0.1, label: "+10% range" },
      {
        tier: 6,
        xp: 192,
        stat: "slowDuration",
        mult: 0.22,
        label: "+22% slow dur",
      },
      { tier: 7, xp: 272, stat: "damage", mult: 0.2, label: "+20% dmg" },
      {
        tier: 8,
        xp: 368,
        stat: "slowDuration",
        mult: 0.28,
        label: "+28% slow dur",
      },
      { tier: 9, xp: 465, stat: "range", mult: 0.15, label: "+15% range" },
    ],
    skill5: {
      xp: 130,
      A: {
        name: "Deep Freeze",
        desc: "+50% slow duration",
        icon: "🧊",
        cost: 70,
        statDelta: { slowDuration: 0.5 },
      },
      B: {
        name: "Nova",
        desc: "Area slow on fire",
        icon: "❄️",
        cost: 70,
        special: "areaFreeze",
      },
    },
    skill10: {
      xp: 575,
      A: {
        name: "Absolute",
        desc: "Freeze fully stops enemy",
        icon: "💀",
        cost: 110,
        statDelta: { slowDuration: 0.5 },
        special: "fullFreeze",
      },
      B: {
        name: "Shatter",
        desc: "Frozen enemies take 2× dmg",
        icon: "💎",
        cost: 110,
        special: "shatterBuff",
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Permafrost",
        desc: "Slowed enemies also lose 30% armor.",
        icon: "🌨️",
        cost: 400,
        special: "armorSlow",
      },
      B: {
        name: "Flash Freeze",
        desc: "Instantly freezes any enemy on first hit.",
        icon: "❄️",
        cost: 400,
        special: "instantFreeze",
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Ice Age",
        desc: "On kill, freeze all nearby enemies 3s.",
        icon: "🏔️",
        cost: 800,
        special: "iceAge",
      },
      B: {
        name: "Absolute Zero",
        desc: "All enemies on map slowed permanently.",
        icon: "🌀",
        cost: 800,
        special: "globalSlow",
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Heat Death",
        desc: "All enemies permanently frozen. Only boss-level HP can break free.",
        icon: "🧊",
        cost: 2000,
        special: "heatDeath",
      },
      B: {
        name: "Cryo Storm",
        desc: "Frozen enemies shatter on death, dealing 500% dmg to nearby enemies.",
        icon: "💠",
        cost: 2000,
        special: "cryoStorm",
      },
    },
  },

  tesla: {
    passives: [
      { tier: 1, xp: 28, stat: "damage", mult: 0.15, label: "+15% dmg" },
      { tier: 2, xp: 64, stat: "range", mult: 0.1, label: "+10% range" },
      { tier: 3, xp: 120, stat: "damage", mult: 0.2, label: "+20% dmg" },
      {
        tier: 4,
        xp: 225,
        stat: "fireRate",
        mult: -0.12,
        label: "−12% cooldown",
      },
      { tier: 6, xp: 360, stat: "damage", mult: 0.25, label: "+25% dmg" },
      { tier: 7, xp: 450, stat: "chainTargets", flat: 1, label: "+1 chain" },
      { tier: 8, xp: 545, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 9, xp: 625, stat: "damage", mult: 0.3, label: "+30% dmg" },
    ],
    skill5: {
      xp: 290,
      A: {
        name: "Conductor",
        desc: "+2 chain targets",
        icon: "🌩️",
        cost: 110,
        statDelta: { chainTargets: 2 },
      },
      B: {
        name: "Surge",
        desc: "+80% dmg per arc",
        icon: "⚡",
        cost: 110,
        statDelta: { damage: 0.8 },
      },
    },
    skill10: {
      xp: 785,
      A: {
        name: "Storm",
        desc: "Chains to 8 targets",
        icon: "🌪️",
        cost: 160,
        statDelta: { chainTargets: 5 },
      },
      B: {
        name: "Overload",
        desc: "Chain stuns 0.3s each",
        icon: "💥",
        cost: 160,
        statDelta: { damage: 0.5 },
        special: "chainStun",
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Godstorm",
        desc: "Arcs pierce ALL shields and immunities. Strips adaptive immunity on hit.",
        icon: "☈",
        cost: 400,
        statDelta: { chainTargets: 3 },
        special: "immunityBreak",
      },
      B: {
        name: "Ball Lightning",
        desc: "Roaming orb zaps nearby enemies.",
        icon: "⚡",
        cost: 400,
        special: "ballLightning",
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Obliterator",
        desc: "Every 5th arc triggers a full-screen pulse.",
        icon: "💀",
        cost: 800,
        special: "arcPulse",
      },
      B: {
        name: "Thundergod",
        desc: "+3 chains, all arcs ignore armor & stealth.",
        icon: "🌩️",
        cost: 800,
        statDelta: { chainTargets: 3 },
        special: "fullPierce",
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Zeus Protocol",
        desc: "Chains to ALL enemies on screen. Each arc deals full damage.",
        icon: "⚡",
        cost: 2000,
        special: "zeusProtocol",
      },
      B: {
        name: "Storm God",
        desc: "Permanent storm field — all enemies take 30 damage/tick passively.",
        icon: "🌩️",
        cost: 2000,
        special: "stormGod",
      },
    },
  },

  inferno: {
    passives: [
      { tier: 1, xp: 28, stat: "burnDamage", flat: 1, label: "+1 burn/tick" },
      { tier: 2, xp: 68, stat: "range", mult: 0.1, label: "+10% range" },
      { tier: 3, xp: 128, stat: "burnDamage", flat: 2, label: "+2 burn/tick" },
      {
        tier: 4,
        xp: 208,
        stat: "burnDuration",
        mult: 0.15,
        label: "+15% burn dur",
      },
      { tier: 6, xp: 368, stat: "burnDamage", flat: 3, label: "+3 burn/tick" },
      { tier: 7, xp: 495, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 8, xp: 648, stat: "burnDamage", flat: 4, label: "+4 burn/tick" },
      {
        tier: 9,
        xp: 785,
        stat: "burnDuration",
        mult: 0.25,
        label: "+25% burn dur",
      },
    ],
    skill5: {
      xp: 265,
      A: {
        name: "Wildfire",
        desc: "+60% burn duration",
        icon: "🔥",
        cost: 120,
        statDelta: { burnDuration: 0.6 },
      },
      B: {
        name: "Floodfire",
        desc: "+40% range, area ignite",
        icon: "🌋",
        cost: 120,
        statDelta: { range: 0.4 },
        special: "areaIgnite",
      },
    },
    skill10: {
      xp: 960,
      A: {
        name: "Hellfire",
        desc: "Burn stacks 3×",
        icon: "☠️",
        cost: 180,
        statDelta: { burnDamage: 2 },
        special: "burnStack",
      },
      B: {
        name: "Meltdown",
        desc: "Burning = −40% armor",
        icon: "⚗️",
        cost: 180,
        special: "armorMelt",
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Phoenix Core",
        desc: "Killed enemies explode, igniting neighbors.",
        icon: "🦅",
        cost: 400,
        special: "deathIgnite",
      },
      B: {
        name: "Cremation",
        desc: "Enemies below 20% HP take 4× burn damage. Berserker stacks reset on kill.",
        icon: "💀",
        cost: 400,
        special: "execute",
        statDelta: { burnDamage: 1 },
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Supernova",
        desc: "Every 6th shot = massive burn AoE.",
        icon: "💢",
        cost: 800,
        special: "supernova",
      },
      B: {
        name: "Hellgate",
        desc: "Permanent fire zone, continuous dmg.",
        icon: "😈",
        cost: 800,
        special: "hellgate",
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Solar Core",
        desc: "All burn damage becomes true damage. Burn stacks cap raised to 10×.",
        icon: "🌞",
        cost: 2000,
        special: "solarCore",
      },
      B: {
        name: "Infernal Realm",
        desc: "Converts the entire map into burning ground. All enemies take continuous damage.",
        icon: "😈",
        cost: 2000,
        special: "infernalRealm",
      },
    },
  },

  // ── VORTEX: XP thresholds reduced ~25% across all tiers so it levels faster ──
  vortex: {
    passives: [
      { tier: 1, xp: 25, stat: "pullForce", flat: 0.1, label: "+0.1 pull" },
      { tier: 2, xp: 55, stat: "splash", mult: 0.1, label: "+10% splash" },
      { tier: 3, xp: 105, stat: "damage", mult: 0.18, label: "+18% dmg" },
      { tier: 4, xp: 175, stat: "pullForce", flat: 0.15, label: "+0.15 pull" },
      { tier: 6, xp: 310, stat: "damage", mult: 0.25, label: "+25% dmg" },
      { tier: 7, xp: 415, stat: "splash", mult: 0.2, label: "+20% splash" },
      { tier: 8, xp: 545, stat: "damage", mult: 0.32, label: "+32% dmg" },
      { tier: 9, xp: 660, stat: "pullForce", flat: 0.2, label: "+0.2 pull" },
    ],
    skill5: {
      xp: 225,
      A: {
        name: "Singularity",
        desc: "+50% pull, +40% splash",
        icon: "🌀",
        cost: 130,
        statDelta: { pullForce: 0.5, splash: 0.4 },
      },
      B: {
        name: "Cyclone",
        desc: "Continuous spin damage",
        icon: "🌪️",
        cost: 130,
        statDelta: { fireRate: -0.5, damage: 0.6 },
        special: "cyclone",
      },
    },
    skill10: {
      xp: 860,
      A: {
        name: "Void Rift",
        desc: "Teleports enemies back 20%",
        icon: "🌌",
        cost: 200,
        special: "teleportBack",
      },
      B: {
        name: "Collapse",
        desc: "Pulls + 3× damage burst",
        icon: "💥",
        cost: 200,
        statDelta: { damage: 2.0 },
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Event Horizon",
        desc: "Enemies in range can't move at all.",
        icon: "⚫",
        cost: 400,
        special: "gravityLock",
      },
      B: {
        name: "Dark Star",
        desc: "Enemies pulled in take 3× dmg from all towers.",
        icon: "🌑",
        cost: 400,
        special: "darkStarDebuff",
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Bulwark Field",
        desc: "Nearby towers take 40% less damage. Gravity-immune bosses pulled at half force.",
        icon: "🛡️",
        cost: 800,
        special: "bulwarkField",
      },
      B: {
        name: "Omega Rift",
        desc: "Creates a rift teleporting enemies back 50%.",
        icon: "🌌",
        cost: 800,
        special: "omegaRift",
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Singularity Rex",
        desc: "Creates a permanent black hole that continuously pulls ALL enemies and deals 200 dmg/tick.",
        icon: "⚫",
        cost: 2000,
        special: "singularityRex",
      },
      B: {
        name: "Reality Fold",
        desc: "Enemies in range are teleported back to spawn every 6 seconds.",
        icon: "🌌",
        cost: 2000,
        special: "realityFold",
      },
    },
  },

  missile: {
    passives: [
      { tier: 1, xp: 44, stat: "damage", mult: 0.15, label: "+15% dmg" },
      { tier: 2, xp: 104, stat: "splash", mult: 0.12, label: "+12% splash" },
      { tier: 3, xp: 192, stat: "damage", mult: 0.2, label: "+20% dmg" },
      {
        tier: 4,
        xp: 312,
        stat: "fireRate",
        mult: -0.1,
        label: "−10% cooldown",
      },
      { tier: 6, xp: 560, stat: "damage", mult: 0.25, label: "+25% dmg" },
      { tier: 7, xp: 720, stat: "splash", mult: 0.2, label: "+20% splash" },
      { tier: 8, xp: 920, stat: "damage", mult: 0.3, label: "+30% dmg" },
      {
        tier: 9,
        xp: 1120,
        stat: "fireRate",
        mult: -0.15,
        label: "−15% cooldown",
      },
    ],
    skill5: {
      xp: 440,
      A: {
        name: "Payload",
        desc: "+50% splash radius, +20% dmg",
        icon: "💥",
        cost: 140,
        statDelta: { splash: 0.5, damage: 0.2 },
      },
      B: {
        name: "Salvo",
        desc: "Fires 2 missiles per shot",
        icon: "🚀",
        cost: 140,
        special: "salvo",
        statDelta: { damage: 0.15 },
      },
    },
    skill10: {
      xp: 1280,
      A: {
        name: "Cluster Warhead",
        desc: "Missile splits into 4 mini-rockets on impact",
        icon: "🌟",
        cost: 200,
        special: "clusterWarhead",
        statDelta: { damage: 0.35 },
      },
      B: {
        name: "Seeker",
        desc: "After impact, seeks 2 nearby enemies",
        icon: "🎯",
        cost: 200,
        special: "seekerChain",
        statDelta: { damage: 0.4 },
      },
    },
    legendary50: {
      unlocksAtWave: 50,
      A: {
        name: "Nuclear Payload",
        desc: "Every 5th missile = full-screen nuke blast",
        icon: "☢️",
        cost: 450,
        special: "nuclearPayload",
      },
      B: {
        name: "Smart Swarm",
        desc: "Fires 6 simultaneous homing missiles",
        icon: "🐝",
        cost: 450,
        special: "smartSwarm",
        statDelta: { damage: 0.3 },
      },
    },
    legendary100: {
      unlocksAtWave: 100,
      A: {
        name: "Armageddon",
        desc: "Continuous barrage — hits all enemies every 3s",
        icon: "💢",
        cost: 900,
        special: "armageddon",
      },
      B: {
        name: "Void Strike",
        desc: "Missiles ignore all armor and immunities",
        icon: "🌌",
        cost: 900,
        special: "fullPierce",
        statDelta: { damage: 0.8 },
      },
    },
    ascension200: {
      unlocksAtWave: 200,
      A: {
        name: "Doomsday Protocol",
        desc: "Every missile triggers a full-screen nuke. Cooldown halved.",
        icon: "☢️",
        cost: 2000,
        special: "doomsdayProtocol",
      },
      B: {
        name: "Hive Mind",
        desc: "Missiles multiply on hit — each explosion spawns 3 new homing missiles.",
        icon: "🐝",
        cost: 2000,
        special: "hiveMind",
      },
    },
  },
};

// ─── TOWERS ───────────────────────────────────────────────────────────────────
export const TOWER_TYPES = {
  basic: {
    name: "Gunner",
    cost: 50,
    damage: 25,
    range: 125,
    fireRate: 50,
    color: "#4ade80",
    projectileColor: "#4ade80",
    projectileSpeed: 5,
    icon: "🗼",
    desc: "Reliable. Balanced DPS.",
    category: "attack",
    unlockedAtLevel: 1,
    weakAgainst: ["fast", "stealth"],
    strongAgainst: ["basic", "armored"],
    damageType: "physical",
    towerHp: 200,
    towerMaxHp: 200,
    attackDamageResist: 0,
  },
  sniper: {
    name: "Sniper",
    cost: 100,
    damage: 105,
    range: 300,
    fireRate: 170,
    color: "#38bdf8",
    projectileColor: "#38bdf8",
    projectileSpeed: 15,
    icon: "🎯",
    desc: "Long range, high single-target.",
    category: "attack",
    unlockedAtLevel: 1,
    weakAgainst: ["swarm", "stealth"],
    strongAgainst: ["armored", "boss_colossus"],
    damageType: "physical",
    towerHp: 140,
    towerMaxHp: 140,
    attackDamageResist: 0,
  },
  cannon: {
    name: "Cannon",
    cost: 120,
    damage: 62,
    range: 110,
    fireRate: 115,
    color: "#f97316",
    projectileColor: "#f97316",
    projectileSpeed: 4,
    splash: 68,
    icon: "💣",
    desc: "Splash damage. Clears groups.",
    category: "attack",
    unlockedAtLevel: 1,
    weakAgainst: ["fast", "spread"],
    strongAgainst: ["swarm", "basic", "boss_titan"],
    damageType: "physical",
    towerHp: 320,
    towerMaxHp: 320,
    attackDamageResist: 0.15,
  },
  laser: {
    name: "Laser",
    cost: 150,
    damage: 9,
    range: 155,
    fireRate: 5,
    color: "#e879f9",
    projectileColor: "#e879f9",
    projectileSpeed: 22,
    icon: "⚡",
    desc: "Rapid beam. Reveals stealth.",
    category: "tech",
    unlockedAtLevel: 2,
    weakAgainst: ["armored"],
    strongAgainst: ["fast", "stealth", "boss_phantom"],
    damageType: "magical",
    towerHp: 110,
    towerMaxHp: 110,
    attackDamageResist: 0,
  },
  freeze: {
    name: "Cryo",
    cost: 80,
    damage: 7,
    range: 120,
    fireRate: 80,
    color: "#a5f3fc",
    projectileColor: "#a5f3fc",
    projectileSpeed: 6,
    slowFactor: 0.35,
    slowDuration: 140,
    icon: "❄️",
    desc: "Slows enemies significantly.",
    category: "support",
    unlockedAtLevel: 2,
    weakAgainst: ["armored"],
    strongAgainst: ["fast", "swarm"],
    damageType: "hybrid",
    towerHp: 180,
    towerMaxHp: 180,
    attackDamageResist: 0,
  },
  tesla: {
    name: "Tesla",
    cost: 180,
    damage: 45,
    range: 130,
    fireRate: 68,
    color: "#fbbf24",
    projectileColor: "#fbbf24",
    projectileSpeed: 18,
    chainTargets: 3,
    chainRange: 80,
    armorPiercing: true,
    icon: "🌩️",
    desc: "Chains 3 targets. Ignores armor.",
    category: "tech",
    unlockedAtLevel: 3,
    weakAgainst: ["stealth"],
    strongAgainst: ["armored", "swarm", "boss_colossus"],
    damageType: "magical",
    towerHp: 240,
    towerMaxHp: 240,
    attackDamageResist: 0.1,
  },
  inferno: {
    name: "Inferno",
    cost: 200,
    damage: 18,
    range: 102,
    fireRate: 20,
    color: "#ef4444",
    projectileColor: "#ef4444",
    projectileSpeed: 8,
    burnDamage: 5,
    burnDuration: 200,
    icon: "🔥",
    desc: "Burns enemies over time.",
    category: "attack",
    unlockedAtLevel: 4,
    weakAgainst: ["armored"],
    strongAgainst: ["fast", "swarm", "stealth", "boss_voidreaper"],
    damageType: "magical",
    towerHp: 150,
    towerMaxHp: 150,
    attackDamageResist: 0,
  },
  vortex: {
    name: "Vortex",
    cost: 250,
    damage: 35,
    range: 160,
    fireRate: 190,
    color: "#818cf8",
    projectileColor: "#818cf8",
    projectileSpeed: 10,
    splash: 90,
    pullForce: 0.55,
    icon: "🌀",
    desc: "Pulls & blasts all nearby.",
    category: "support",
    unlockedAtLevel: 5,
    weakAgainst: [],
    strongAgainst: ["swarm", "spread", "fast"],
    damageType: "hybrid",
    towerHp: 190,
    towerMaxHp: 190,
    attackDamageResist: 0.05,
  },
  missile: {
    name: "Warhead",
    cost: 280,
    damage: 190,
    range: 350,
    fireRate: 290,
    color: "#f43f5e",
    projectileColor: "#f43f5e",
    projectileSpeed: 2.8,
    splash: 55,
    homing: true,
    icon: "🚀",
    desc: "Homing missiles. Never misses.",
    category: "attack",
    unlockedAtLevel: 3,
    weakAgainst: [],
    strongAgainst: ["fast", "spread", "boss_phantom"],
    damageType: "physical",
    towerHp: 160,
    towerMaxHp: 160,
    attackDamageResist: 0.05,
  },
};

export const STEALTH_COUNTERS = ["laser"];

export const TOWER_CATEGORY_CAPS = {
  attack: { label: "Attack", icon: "⚔️", cap: 10 },
  support: { label: "Support", icon: "🛡️", cap: 5 },
  tech: { label: "Tech", icon: "🔬", cap: 6 },
};

// ─── ENEMIES ──────────────────────────────────────────────────────────────────
export const ENEMY_TYPES = {
  basic: {
    name: "Grunt",
    hp: 105,
    speed: 1.25,
    reward: 10,
    color: "#ef4444",
    size: 10,
    armor: 0,
    stealth: false,
    icon: "👾",
    desc: "Standard infantry.",
    lore: "Mass-produced shock troops. Individually weak, dangerous in numbers.",
    tip: "Any tower handles these. Prioritize faster threats.",
    immunities: [],
    counterNote: "",
    attackDps: 2,
    attackRange: 38,
    physicalResist: 0,
    magicalResist: 0,
  },
  fast: {
    name: "Raider",
    hp: 72,
    speed: 3.1,
    reward: 16,
    color: "#facc15",
    size: 8,
    armor: 0,
    stealth: false,
    icon: "💨",
    desc: "Extremely fast. Hard to hit.",
    lore: "Overcharged scout units. They'll be at your base before you blink.",
    tip: "Cryo towers are critical. Place them early on the path.",
    immunities: [],
    counterNote: "Use Cryo to slow",
    attackDps: 1,
    attackRange: 32,
    physicalResist: 0,
    magicalResist: 0,
  },
  armored: {
    name: "Tank",
    hp: 225,
    speed: 0.65,
    reward: 28,
    color: "#94a3b8",
    size: 14,
    armor: 0.45,
    stealth: false,
    icon: "🛡️",
    desc: "Heavy armor. Resists non-piercing shots.",
    lore: "Walking fortresses. Standard weaponry barely scratches them.",
    tip: "Tesla or Sniper with armorPiercing. Cannon splash also works.",
    immunities: [],
    counterNote: "Tesla or Sniper pierces armor",
    attackDps: 6,
    attackRange: 40,
    physicalResist: 0,
    magicalResist: 0.18,
  },
  swarm: {
    name: "Swarm",
    hp: 30,
    speed: 2.5,
    reward: 5,
    color: "#fb923c",
    size: 7,
    armor: 0,
    stealth: false,
    icon: "🐝",
    desc: "Countless. Overwhelm with numbers.",
    lore: "Bioengineered insectoids released in massive quantities.",
    tip: "Cannon splash is your best friend. One shot clears a cluster.",
    immunities: [],
    counterNote: "Cannon splash clears groups",
    attackDps: 0.8,
    attackRange: 28,
    physicalResist: 0,
    magicalResist: 0,
  },
  stealth: {
    name: "Ghost",
    hp: 115,
    speed: 1.8,
    reward: 22,
    color: "#a78bfa",
    size: 9,
    armor: 0,
    stealth: true,
    icon: "👻",
    desc: "INVISIBLE — most towers cannot target it.",
    lore: "Phase-shifted infiltrators. They exist in a frequency most sensors miss.",
    tip: "One Laser tower reveals and kills all stealth. Without it, they're unstoppable.",
    immunities: [],
    counterNote: "⚠ Laser ONLY can target stealth",
    requiresCounter: "laser",
    attackDps: 4,
    attackRange: 42,
    physicalResist: 0.22,
    magicalResist: 0,
  },
  spread: {
    name: "Brood",
    hp: 175,
    speed: 1.0,
    reward: 38,
    color: "#f0abfc",
    size: 12,
    armor: 0.225,
    stealth: false,
    icon: "🌸",
    desc: "Splits into 4 swarms on death.",
    lore: "A bio-weapon that turns defeat into multiplication.",
    tip: "Kill fast before reaching end. Cannon splash on the death cluster.",
    immunities: [],
    counterNote: "Kill fast before it reaches end",
    spawnsOnDeath: "swarm",
    spawnCount: 4,
    attackDps: 3,
    attackRange: 38,
    physicalResist: 0,
    magicalResist: 0,
  },
  healer: {
    name: "Healer",
    hp: 175,
    speed: 1.1,
    reward: 45,
    color: "#4ade80",
    size: 10,
    armor: 0.1,
    stealth: false,
    icon: "⚕️",
    desc: "Heals nearby allies every second. Priority target.",
    lore: "Field medics keep the horde fighting. One Medic can undo an entire wave of damage.",
    tip: "Kill Medics immediately. Sniper or Laser locks on fast. Never let one reach mid-path.",
    immunities: [],
    counterNote: "⚠ Kill first — heals all nearby enemies 8% HP/sec",
    physicalResist: 0,
    magicalResist: 0,
    attackDps: 1,
    attackRange: 30,
    healRadius: 90,
    healRate: 0.08,
    healInterval: 60,
  },
  boss_colossus: {
    name: "Colossus",
    hp: 4000,
    speed: 0.65,
    reward: 140,
    color: "#dc2626",
    size: 24,
    armor: 0.5,
    stealth: false,
    icon: "💀",
    isBoss: true,
    desc: "Armored walker. Cryo is USELESS against it.",
    lore: "A siege machine forged in the void. Cryo fields shatter against its hull.",
    tip: "Tesla chains pierce its armor. Stack 2+ Teslas for consistent DPS.",
    immunities: ["freeze"],
    counterNote: "⚠ Cryo cannot slow it. Use Tesla (armor-pierce chains).",
    weakness: "tesla",
    weaknessHint: "Tesla chains pierce its armor and ignore Cryo-immunity.",
    phaseAt: 0.5,
    phaseBoost: { speed: 1.5, armorDelta: 0.18 },
    bossAbility: "enrage",
    spawnsOnDamage: { type: "armored", every: 400, count: 2 },
    stunImmunityBase: 180,
    lootDrop: {
      type: "speed_boost",
      duration: 600,
      label: "⚡ Speed Frenzy 10s",
    },
    attackDps: 22,
    attackRange: 55,
    physicalResist: 0,
    magicalResist: 0.12,
  },
  boss_phantom: {
    name: "Phantom Lord",
    hp: 2500,
    speed: 1.4,
    reward: 160,
    color: "#7c3aed",
    size: 22,
    armor: 0.15,
    stealth: true,
    icon: "🌑",
    isBoss: true,
    desc: "Stealth wraith. Splash and bullets pass THROUGH it.",
    lore: "It exists between dimensions. Physical weapons phase through its form.",
    tip: "Laser only. Get 2+ Lasers before this wave or you lose lives guaranteed.",
    immunities: ["cannon", "basic"],
    counterNote: "⚠ Cannon & Gunner miss entirely. Only Laser locks on.",
    weakness: "laser",
    weaknessHint:
      "Laser auto-targets through stealth — the only tower that can hit it.",
    phaseAt: 0.35,
    phaseBoost: { speed: 0.6 },
    bossAbility: "phase",
    lootDrop: {
      type: "damage_boost",
      duration: 480,
      label: "💥 Damage Surge 8s",
    },
    attackDps: 14,
    attackRange: 60,
    physicalResist: 0,
    magicalResist: 0,
  },
  boss_titan: {
    name: "Titan Hive",
    hp: 5000,
    speed: 0.4,
    reward: 220,
    color: "#b45309",
    size: 28,
    armor: 0.45,
    stealth: false,
    icon: "🦂",
    isBoss: true,
    desc: "Hive-mind colossus. Tech weapons fail against its shell.",
    lore: "A living fortress that births soldiers from its own body.",
    tip: "Cannon splash is the only answer. Ignore the swarm children — focus the Titan.",
    immunities: ["sniper", "laser"],
    counterNote: "⚠ Sniper & Laser bounce off. Use Cannon heavy splash.",
    weakness: "cannon",
    weaknessHint: "Cannon splash bypasses its tech-immunity — blast it.",
    spawnsOnDamage: { type: "swarm", every: 280, count: 4 },
    phaseAt: 0.55,
    phaseBoost: { speed: 0.25 },
    bossAbility: "spawn",
    lootDrop: { type: "gold_shower", amount: 180, label: "💰 +180g Drop" },
    attackDps: 30,
    attackRange: 55,
    physicalResist: 0,
    magicalResist: 0,
  },
  boss_voidreaper: {
    name: "Void Reaper",
    hp: 3600,
    speed: 1.0,
    reward: 200,
    color: "#312e81",
    size: 26,
    armor: 0.35,
    stealth: false,
    icon: "☠️",
    isBoss: true,
    desc: "Voidborn destroyer. Physical/cold damage is ABSORBED.",
    lore: "A tear in space-time given form. It feeds on the energy of your weapons.",
    tip: "Inferno burn ignores void shields. Stack Inferno towers before this wave.",
    immunities: ["basic", "freeze", "cannon"],
    counterNote:
      "⚠ Gunner/Cryo/Cannon all absorbed. Inferno burns through void shields.",
    weakness: "inferno",
    weaknessHint:
      "Void energy is flammable — Inferno burn ignores its shields.",
    phaseAt: 0.45,
    phaseBoost: { speed: 0.45, armorDelta: -0.3 },
    bossAbility: "drain",
    lootDrop: { type: "lives_restore", amount: 3, label: "❤️ +3 Lives" },
    attackDps: 18,
    attackRange: 58,
    physicalResist: 0.28,
    magicalResist: 0,
  },
  chrono_raider: {
    name: "Chrono Raider",
    hp: 95,
    speed: 3.2,
    reward: 28,
    color: "#c084fc",
    size: 8,
    armor: 0,
    stealth: false,
    icon: "⚡",
    desc: "Immune to ALL slow effects. Extremely fast.",
    lore: "Phase-shifted speed demons. Time itself cannot touch them.",
    tip: "No slow works. Use stun from Tesla chainStun or high single-target DPS.",
    immunities: ["freeze"],
    counterNote: "⚠ Immune to ALL slow. Only stuns or raw DPS work.",
    requiresCounter: "tesla",
    attackDps: 2,
    attackRange: 32,
    physicalResist: 0,
    magicalResist: 0.1,
  },
  phantom_swarm: {
    name: "Phantom Swarm",
    hp: 45,
    speed: 2.2,
    reward: 12,
    color: "#818cf8",
    size: 7,
    armor: 0,
    stealth: true,
    icon: "🔮",
    desc: "Stealth swarm. Invisible AND numerous.",
    lore: "They cloaked themselves in void energy and kept multiplying.",
    tip: "Laser is mandatory. Without it these are completely invisible.",
    immunities: [],
    counterNote: "⚠ Stealth swarm — Laser essential",
    requiresCounter: "laser",
    attackDps: 1,
    attackRange: 28,
    physicalResist: 0,
    magicalResist: 0,
  },
  juggernaut: {
    name: "Juggernaut",
    hp: 520,
    speed: 0.9,
    reward: 55,
    color: "#dc2626",
    size: 16,
    armor: 0.55,
    stealth: false,
    icon: "🦾",
    desc: "Immune to ALL crowd control. Shrugs off stuns, slows, pulls.",
    lore: "Built to ignore every field effect your engineers can devise.",
    tip: "Raw damage only. Inferno burn and Sniper work best.",
    immunities: ["freeze"],
    counterNote: "⚠ CC-immune. Only raw damage works — Inferno or Sniper.",
    attackDps: 12,
    attackRange: 45,
    physicalResist: 0,
    magicalResist: 0.15,
    stunImmunityBase: 999999,
  },
  void_carrier: {
    name: "Void Carrier",
    hp: 310,
    speed: 0.7,
    reward: 70,
    color: "#7c3aed",
    size: 14,
    armor: 0.3,
    stealth: false,
    icon: "🌑",
    desc: "Spawns 3 Phantom Swarms on death AND every 8 seconds.",
    lore: "A living hive that bleeds shadows.",
    tip: "Kill fast before it spawns too many swarms. Cannon splash + Laser combo.",
    immunities: [],
    counterNote: "Kill fast — spawns phantom swarms continuously",
    spawnsOnDeath: "phantom_swarm",
    spawnCount: 3,
    spawnsOnDamage: { type: "phantom_swarm", every: 480, count: 2 },
    attackDps: 6,
    attackRange: 40,
    physicalResist: 0,
    magicalResist: 0,
  },
};

// ─── MAPS ─────────────────────────────────────────────────────────────────────
export const MAPS = {
  valley: {
    name: "Ember Valley",
    description: "Classic winding valley. Good for learning.",
    unlockedAtLevel: 1,
    theme: {
      path: "#1e293b",
      bg: "#0f172a",
      pathBorder: "#334155",
      accent: "#4ade80",
    },
    waypoints: [
      { col: 0, row: 10 },
      { col: 6, row: 10 },
      { col: 6, row: 2 },
      { col: 13, row: 2 },
      { col: 13, row: 17 },
      { col: 20, row: 17 },
      { col: 20, row: 6 },
      { col: 26, row: 6 },
      { col: 26, row: 14 },
      { col: 29, row: 14 },
    ],
    mapBonus: { type: "gold", value: 0.15, label: "💰 +15% gold drops" },
  },
  spiral: {
    name: "Vortex Spiral",
    description: "Long spiral. More placement opportunities.",
    unlockedAtLevel: 2,
    theme: {
      path: "#1c1917",
      bg: "#0c0a09",
      pathBorder: "#44403c",
      accent: "#f97316",
    },
    waypoints: [
      { col: 0, row: 1 },
      { col: 28, row: 1 },
      { col: 28, row: 8 },
      { col: 14, row: 8 },
      { col: 14, row: 3 },
      { col: 8, row: 3 },
      { col: 8, row: 18 },
      { col: 22, row: 18 },
      { col: 22, row: 13 },
      { col: 29, row: 13 },
    ],
    mapBonus: { type: "range", value: 0.1, label: "🔭 +10% tower range" },
  },
  gauntlet: {
    name: "Iron Gauntlet",
    description: "Short brutal path. Expert only.",
    unlockedAtLevel: 3,
    theme: {
      path: "#1e1b4b",
      bg: "#0f0e2a",
      pathBorder: "#3730a3",
      accent: "#818cf8",
    },
    waypoints: [
      { col: 0, row: 5 },
      { col: 10, row: 5 },
      { col: 10, row: 17 },
      { col: 3, row: 17 },
      { col: 3, row: 11 },
      { col: 18, row: 11 },
      { col: 18, row: 2 },
      { col: 25, row: 2 },
      { col: 25, row: 16 },
      { col: 29, row: 16 },
    ],
    mapBonus: { type: "damage", value: 0.12, label: "⚔️ +12% tower damage" },
  },
  abyss: {
    name: "Void Abyss",
    description: "Maximum difficulty. Chaotic long run.",
    unlockedAtLevel: 4,
    theme: {
      path: "#2d1b69",
      bg: "#0d0621",
      pathBorder: "#4c1d95",
      accent: "#e879f9",
    },
    waypoints: [
      { col: 0, row: 18 },
      { col: 27, row: 18 },
      { col: 27, row: 12 },
      { col: 5, row: 12 },
      { col: 5, row: 6 },
      { col: 23, row: 6 },
      { col: 23, row: 1 },
      { col: 12, row: 1 },
      { col: 12, row: 9 },
      { col: 29, row: 9 },
    ],
    mapBonus: { type: "fireRate", value: 0.1, label: "⚡ +10% fire rate" },
  },
  dynamic: generateDynamicMap({ cols: 30, rows: 20, complexity: 7 }),
};

// ─── LEVELS ───────────────────────────────────────────────────────────────────
export const LEVELS = [
  {
    id: 1,
    name: "Ember Valley",
    map: "valley",
    xpMult: 1.4,
    waves: 8,
    startGold: 320,
    startLives: 20,
    unlockedTowers: ["basic", "sniper", "cannon"],
    towerCaps: { attack: 8, support: 3, tech: 3 },
    bossWaves: { 7: "boss_colossus" },
    description: "Learn the ropes. The AI is watching.",
  },
  {
    id: 2,
    name: "Vortex Spiral",
    map: "spiral",
    xpMult: 1.2,
    waves: 10,
    startGold: 280,
    startLives: 18,
    unlockedTowers: ["basic", "sniper", "cannon", "laser", "freeze"],
    towerCaps: { attack: 7, support: 4, tech: 4 },
    bossWaves: { 8: "boss_phantom", 10: "boss_colossus" },
    description: "Two bosses. Discover their weaknesses fast.",
  },
  {
    id: 3,
    name: "Iron Gauntlet",
    map: "gauntlet",
    xpMult: 1.0,
    waves: 12,
    startGold: 260,
    startLives: 16,
    unlockedTowers: [
      "basic",
      "sniper",
      "cannon",
      "laser",
      "freeze",
      "tesla",
      "missile",
    ],
    towerCaps: { attack: 6, support: 4, tech: 5 },
    bossWaves: { 5: "boss_colossus", 9: "boss_phantom", 12: "boss_titan" },
    description: "Three bosses. Every cap slot matters.",
  },
  {
    id: 4,
    name: "Void Abyss",
    map: "abyss",
    xpMult: 0.85,
    waves: 14,
    startGold: 240,
    startLives: 14,
    unlockedTowers: [
      "basic",
      "sniper",
      "cannon",
      "laser",
      "freeze",
      "tesla",
      "inferno",
      "missile",
    ],
    towerCaps: { attack: 6, support: 3, tech: 5 },
    bossWaves: {
      4: "boss_phantom",
      8: "boss_titan",
      11: "boss_voidreaper",
      14: "boss_colossus",
    },
    description: "Tight caps, brutal bosses. Every decision is critical.",
  },
  {
    id: 5,
    name: "Final Crucible",
    map: "abyss",
    xpMult: 0.7,
    waves: 16,
    startGold: 220,
    startLives: 12,
    unlockedTowers: [
      "basic",
      "sniper",
      "cannon",
      "laser",
      "freeze",
      "tesla",
      "inferno",
      "vortex",
      "missile",
    ],
    towerCaps: { attack: 5, support: 3, tech: 5 },
    bossWaves: {
      4: "boss_colossus",
      8: "boss_phantom",
      11: "boss_titan",
      14: "boss_voidreaper",
      16: "boss_titan",
    },
    description: "Full arsenal. Max AI aggression. Survive if you can.",
  },
];

// ─── ENDLESS MODE ─────────────────────────────────────────────────────────────
export const ENDLESS_CONFIG = {
  id: 99,
  name: "Endless Siege",
  xpMult: 1.0,
  isEndless: true,
  startGold: 340,
  startLives: 22,
  unlockedTowers: [
    "basic",
    "sniper",
    "cannon",
    "laser",
    "freeze",
    "tesla",
    "inferno",
    "vortex",
    "missile",
  ],
  towerCaps: { attack: 10, support: 6, tech: 7 },
  waves: Infinity,
  bossWaves: {},
  mechanics: {
    10: { label: "Elite Units", desc: "Enemies gain 20% armor permanently" },
    20: { label: "Speed Surge", desc: "All enemies permanently +15% faster" },
    30: { label: "Boss Escort", desc: "Bosses now arrive with armored guard" },
    40: { label: "Void Rifts", desc: "Stealth enemies appear in all waves" },
    50: { label: "Titan Protocol", desc: "Boss HP x2, double boss waves" },
    75: { label: "Juggernaut Age", desc: "Juggernauts appear in every wave" },
    100: { label: "Apex Tide", desc: "All enemies gain +50% all stats" },
    150: {
      label: "Void Storm",
      desc: "Boss HP x3. Chrono Raiders every wave.",
    },
    200: {
      label: "God Tier",
      desc: "Enemy HP x5. Ascension upgrades unlocked.",
    },
    300: {
      label: "Singularity",
      desc: "Enemies evolve every 5 kills instead of 80.",
    },
    500: {
      label: "Extinction Event",
      desc: "Every 3rd wave is a double-boss modifier wave.",
    },
  },
  bossSchedule: [
    "boss_colossus",
    "boss_phantom",
    "boss_titan",
    "boss_voidreaper",
  ],
};

// ─── ABILITIES ────────────────────────────────────────────────────────────────
export const ABILITIES = {
  airstrike: {
    name: "Airstrike",
    icon: "✈️",
    desc: "Deals 500 damage to all enemies on screen",
    cooldown: 720, // was 900 — reduced so it's usable each boss wave
    cost: 0,
    color: "#ef4444",
  },
  emp: {
    name: "EMP Blast",
    icon: "🌐",
    desc: "Stuns all enemies for 3 seconds",
    cooldown: 540, // was 720
    cost: 0,
    color: "#fbbf24",
  },
  reinforce: {
    name: "Reinforce",
    icon: "🏰",
    desc: "All towers fire 2× faster for 8 seconds",
    cooldown: 960, // was 1200
    cost: 0,
    color: "#4ade80",
  },
  // ── New ability: unlocks at wave 50 ──────────────────────────────────────
  overload: {
    name: "Overload",
    icon: "⚡",
    desc: "All towers deal 3× damage for 5 seconds. Unlocks wave 50+.",
    cooldown: 1800,
    cost: 0,
    color: "#fbbf24",
    unlocksAtWave: 50,
  },
  // ── New ability: unlocks at wave 100 ─────────────────────────────────────
  mass_repair: {
    name: "Mass Repair",
    icon: "🔧",
    desc: "Instantly fully repairs all towers and grants 8 seconds of invulnerability to towers. Wave 100+.",
    cooldown: 2400,
    cost: 0,
    color: "#4ade80",
    unlocksAtWave: 100,
  },
};

// ─── SYNERGIES ────────────────────────────────────────────────────────────────
export const SYNERGIES = {
  freeze_cannon: {
    towers: ["freeze", "cannon"],
    name: "Shatter",
    desc: "Slowed enemies take +50% splash damage",
    color: "#a5f3fc",
    bonus: { splashDamageVsSlowed: 0.5 },
  },
  laser_tesla: {
    towers: ["laser", "tesla"],
    name: "Overcharge",
    desc: "Tesla chains to laser-revealed stealth targets",
    color: "#fbbf24",
    bonus: { teslaRevealStealth: true },
  },
  inferno_cannon: {
    towers: ["inferno", "cannon"],
    name: "Napalm Zone",
    desc: "Cannon splash leaves burning ground for 3s",
    color: "#ef4444",
    bonus: { burnGround: true },
  },
  sniper_freeze: {
    towers: ["sniper", "freeze"],
    name: "Frozen Target",
    desc: "Sniper crits on slowed enemies (+80% dmg)",
    color: "#38bdf8",
    bonus: { sniperCritOnSlowed: 0.8 },
  },
  // ── New synergies ─────────────────────────────────────────────────────────
  tesla_missile: {
    towers: ["tesla", "missile"],
    name: "Guided Storm",
    desc: "Missiles gain +40% damage vs stunned enemies",
    color: "#f43f5e",
    bonus: { missileDmgVsStunned: 0.4 },
  },
  vortex_inferno: {
    towers: ["vortex", "inferno"],
    name: "Vortex Flame",
    desc: "Pulled enemies take 2× burn damage",
    color: "#818cf8",
    bonus: { burnDmgVsPulled: 2.0 },
  },
  vortex_cannon: {
    towers: ["vortex", "cannon"],
    name: "Gravity Bomb",
    desc: "Cannon splash radius +30% on pulled enemies",
    color: "#f97316",
    bonus: { splashRadiusVsPulled: 0.3 },
  },
  laser_sniper: {
    towers: ["laser", "sniper"],
    name: "Marked Target",
    desc: "Sniper deals +60% damage to enemies hit by laser in last 2s",
    color: "#e879f9",
    bonus: { sniperDmgVsLaserTagged: 0.6 },
  },
};

// ─── ADMIN CONFIG ─────────────────────────────────────────────────────────────
export const ADMIN_CONFIG = {
  ai: {
    learningRate: 0.15,
    minWavesBeforeAdapt: 2,
    crossGameMemoryDecay: 0.82,
    maxExploitAttempts: 4,
    bossHpScaling: 2.3,
    enemyHpPerWave: 0.09,
    enemySpeedPerWave: 0.015,
    endlessHpPerWave: 0.24,
    endlessSpeedPerWave: 0.017,
    lateGameExpScale: 1.22,
  },
  economy: {
    waveClearBonus: 18,
    waveClearBonusPerWave: 4,
    towerSellRatio: 0.6,
    fortifyCostBase: 280,
    fortifyCostPerPurchase: 450,
    maxFortifyLevel: 20,
  },
  visual: {
    showBossImmunityHints: true,
    bossWarningFrames: 200,
  },
  enemyEvolution: {
    killThresholdPerType: 80,
    maxEvolutionsPerType: 2,
    evolutionNotifyFrames: 180,
  },
  // ── CONTINUE SYSTEM ───────────────────────────────────────────────────────
  // Controls the "Last Chance" continue feature.
  // When lives hit 0, players can spend a continue (max 3 per run)
  // instead of ending immediately.
  continueSystem: {
    maxContinues: 3, // total continues allowed per run
    livesOnContinue: 5, // lives restored on each continue
    goldCostBase: 150, // gold cost for first continue
    goldCostPerUse: 150, // increases by this each subsequent use
  },
};

export const STARTING_GOLD = 350;
export const STARTING_LIVES = 25;

// ─── WAVE MODIFIERS ───────────────────────────────────────────────────────────
export const WAVE_MODIFIERS = [
  {
    id: "armored_tide",
    name: "Armored Tide",
    icon: "🛡️",
    color: "#94a3b8",
    desc: "All enemies gain +40% armor",
    type: "debuff",
    weight: 10,
    apply: { enemyArmorBonus: 0.4 },
  },
  {
    id: "haste_protocol",
    name: "Haste Protocol",
    icon: "💨",
    color: "#facc15",
    desc: "All enemies move 60% faster",
    type: "debuff",
    weight: 10,
    apply: { enemySpeedMult: 0.6 },
  },
  {
    id: "fog_of_war",
    name: "Fog of War",
    icon: "🌫️",
    color: "#64748b",
    desc: "All tower ranges cut by 30%",
    type: "debuff",
    weight: 8,
    apply: { towerRangeMult: -0.3 },
  },
  {
    id: "void_surge",
    name: "Void Surge",
    icon: "👻",
    color: "#a78bfa",
    desc: "All enemies gain stealth — Laser essential",
    type: "debuff",
    weight: 7,
    apply: { allStealth: true },
  },
  {
    id: "elite_squad",
    name: "Elite Squad",
    icon: "💀",
    color: "#ef4444",
    desc: "3 elites spawn: 5× HP, 8× reward",
    type: "debuff",
    weight: 8,
    apply: { eliteCount: 3, eliteHpMult: 5, eliteRewardMult: 8 },
  },
  {
    id: "regenerating_horde",
    name: "Regenerating Horde",
    icon: "💚",
    color: "#4ade80",
    desc: "Enemies slowly recover HP — kill fast!",
    type: "debuff",
    weight: 8,
    apply: { enemyRegenRate: 0.0018 },
  },
  {
    id: "gold_rush",
    name: "Gold Rush",
    icon: "💰",
    color: "#facc15",
    desc: "Enemies drop 2.5× gold this wave",
    type: "buff",
    weight: 12,
    apply: { enemyRewardMult: 2.5 },
  },
  {
    id: "overcharge",
    name: "Overcharge",
    icon: "🔋",
    color: "#4ade80",
    desc: "All towers fire 45% faster this wave",
    type: "buff",
    weight: 10,
    apply: { towerFireRateMult: 0.45 },
  },
  {
    id: "armor_melt",
    name: "Armor Melt",
    icon: "🔥",
    color: "#f97316",
    desc: "All enemy armor reduced by 65%",
    type: "buff",
    weight: 10,
    apply: { enemyArmorMelt: 0.65 },
  },
  {
    id: "double_time",
    name: "Double Time",
    icon: "⏩",
    color: "#818cf8",
    desc: "2× enemies spawn, 1.8× gold reward",
    type: "chaos",
    weight: 9,
    apply: { enemyCountMult: 2, enemyRewardMult: 1.8 },
  },
  {
    id: "empowered_boss",
    name: "Empowered Boss",
    icon: "👑",
    color: "#fbbf24",
    desc: "Boss has 2× HP — kills drop legendary loot",
    type: "chaos",
    weight: 6,
    apply: { bossHpMult: 2, bossLegendaryLoot: true },
  },
  {
    id: "tower_silence",
    name: "Tower Silence",
    icon: "🔇",
    color: "#ef4444",
    desc: "One random tower type is disabled this wave",
    type: "chaos",
    weight: 7,
    apply: { silenceRandom: true },
  },
  {
    id: "dual_front",
    name: "Dual Front",
    icon: "⚔️",
    color: "#f43f5e",
    desc: "Enemies attack from TWO entry points simultaneously",
    type: "chaos",
    weight: 12,
    apply: { dualFront: true },
  },
  // ── New late-game modifiers ───────────────────────────────────────────────
  {
    id: "xp_surge",
    name: "XP Surge",
    icon: "⭐",
    color: "#fbbf24",
    desc: "All towers gain 3× XP this wave",
    type: "buff",
    weight: 8,
    apply: { towerXpMult: 3.0 },
  },
  {
    id: "gold_fortress",
    name: "Gold Fortress",
    icon: "🏰",
    color: "#facc15",
    desc: "Earn 500g bonus if no tower takes damage this wave",
    type: "buff",
    weight: 6,
    apply: { noDamageGoldBonus: 500 },
  },
];

// ─── BOSS MUTATIONS ───────────────────────────────────────────────────────────
export const BOSS_MUTATIONS = [
  {
    id: "iron_shell",
    name: "Iron Shell",
    icon: "🛡️",
    desc: "+40% armor",
    minWave: 30,
    maxWave: 65,
    apply: { armorBonus: 0.4 },
  },
  {
    id: "overclocked",
    name: "Overclocked",
    icon: "⚡",
    desc: "+70% speed",
    minWave: 30,
    maxWave: 65,
    apply: { speedMult: 1.7 },
  },
  {
    id: "phase_cloak",
    name: "Phase Cloak",
    icon: "👻",
    desc: "Stealth below 60% HP",
    minWave: 30,
    maxWave: 75,
    apply: { stealthBelowHp: 0.6 },
  },
  {
    id: "regenerating",
    name: "Regenerating",
    icon: "💚",
    desc: "Recovers 0.8% max HP/sec",
    minWave: 30,
    maxWave: 70,
    apply: { regenRate: 0.008 },
  },
  {
    id: "colossal",
    name: "Colossal",
    icon: "🌍",
    desc: "+120% HP, −30% speed",
    minWave: 30,
    maxWave: 80,
    apply: { hpMult: 2.2, speedMult: 0.7 },
  },
  {
    id: "enraged_escort",
    name: "Enraged Escort",
    icon: "🗡️",
    desc: "Escort units have 3× HP",
    minWave: 30,
    maxWave: 60,
    apply: { escortHpMult: 3 },
  },
  {
    id: "twin_spawn",
    name: "Twin Spawn",
    icon: "👥",
    desc: "Spawns a 60%-HP clone at 50% health",
    minWave: 30,
    maxWave: 75,
    apply: { twinAt: 0.5, twinHpFraction: 0.6 },
  },
  {
    id: "stun_immune",
    name: "Stun Immune",
    icon: "🔰",
    desc: "Fully immune to stuns and slows",
    minWave: 30,
    maxWave: 80,
    apply: { immuneStunSlow: true },
  },
  {
    id: "void_step",
    name: "Void Step",
    icon: "🌀",
    desc: "Teleports forward 25% of path every 12 seconds",
    minWave: 50,
    apply: { voidStep: true, voidStepInterval: 720, voidStepFraction: 0.25 },
  },
  {
    id: "berserker",
    name: "Berserker",
    icon: "🔥",
    desc: "Each 5% HP lost = +8% speed, stacks up to ×3",
    minWave: 50,
    apply: {
      berserker: true,
      berserkerStackSize: 0.05,
      berserkerSpeedBonus: 0.08,
      berserkerMaxStacks: 3,
    },
  },
  {
    id: "adaptive_immunity",
    name: "Adaptive",
    icon: "🧬",
    desc: "Gains immunity to the last tower type that hit it, cycles every 8s",
    minWave: 55,
    apply: { adaptiveImmunity: true, adaptiveInterval: 480 },
  },
  {
    id: "mirror_shield",
    name: "Mirror Shield",
    icon: "🪞",
    desc: "Reflects 10% of incoming damage back to nearest tower",
    minWave: 70,
    apply: {
      mirrorShield: 0.1,
      mirrorShieldCap: 15,
      mirrorShieldCooldown: 180,
    },
  },
  {
    id: "splinter_death",
    name: "Splinter",
    icon: "💥",
    desc: "On death splits into 3 copies at 30% HP each",
    minWave: 70,
    apply: { splinterDeath: true, splinterCount: 3, splinterHpFraction: 0.3 },
  },
  {
    id: "leech",
    name: "Leech",
    icon: "🩸",
    desc: "Heals 3% max HP for each tower it damages",
    minWave: 75,
    apply: { leech: 0.008 },
  },
  {
    id: "gravity_immune",
    name: "Gravity Immune",
    icon: "⚫",
    desc: "Immune to vortex pull and knockback. +20% HP.",
    minWave: 70,
    apply: { gravityImmune: true, hpMult: 1.2 },
  },
  {
    id: "rapid_regen",
    name: "Rapid Regen",
    icon: "💉",
    desc: "Heals 3% HP/sec. Phase 2 doubles regen.",
    minWave: 75,
    apply: { regenRate: 0.008, phase2RegenMult: 1.5 },
  },
  {
    id: "phantom_triple",
    name: "Phantom Triple",
    icon: "👁️",
    desc: "Stealth + twin spawn + immune to stuns",
    minWave: 80,
    apply: {
      stealthBelowHp: 0.75,
      twinAt: 0.4,
      twinHpFraction: 0.5,
      immuneStunSlow: true,
    },
  },
  {
    id: "fortress",
    name: "Fortress",
    icon: "🏰",
    desc: "+80% armor, +150% HP, attacks towers for double damage",
    minWave: 85,
    apply: { armorBonus: 0.8, hpMult: 2.5, towerDamageMult: 1.5 },
  },
  {
    id: "apex_predator",
    name: "Apex Predator",
    icon: "☠️",
    desc: "Every stat +50%. Void steps every 8s. Immune to freeze.",
    minWave: 90,
    apply: {
      hpMult: 1.5,
      speedMult: 1.5,
      armorBonus: 0.3,
      voidStep: true,
      voidStepInterval: 480,
      voidStepFraction: 0.2,
      immuneStunSlow: true,
    },
  },
];

// ─── ENEMY EVOLUTION TABLE ────────────────────────────────────────────────────
export const ENEMY_EVOLUTIONS = {
  basic_vs_cannon: {
    id: "basic_vs_cannon",
    enemyType: "basic",
    triggeredByTower: "cannon",
    name: "Scatter Formation",
    icon: "💨",
    desc: "Grunts spread apart — cannon splash hits only one at a time",
    apply: { scatterFormation: true, size: -2 },
  },
  basic_vs_basic: {
    id: "basic_vs_basic",
    enemyType: "basic",
    triggeredByTower: "basic",
    name: "Hardened Grunts",
    icon: "🛡️",
    desc: "Grunts gain +40% HP and 15% armor",
    apply: { hpMult: 1.4, armorBonus: 0.15 },
  },
  fast_vs_freeze: {
    id: "fast_vs_freeze",
    enemyType: "fast",
    triggeredByTower: "freeze",
    name: "Thermal Raiders",
    icon: "🔥",
    desc: "Raiders become immune to slow effects",
    apply: { immuneSlow: true },
  },
  fast_vs_sniper: {
    id: "fast_vs_sniper",
    enemyType: "fast",
    triggeredByTower: "sniper",
    name: "Evasive Maneuvers",
    icon: "💫",
    desc: "Raiders have 25% chance to dodge single-target shots",
    apply: { dodgeChance: 0.25 },
  },
  armored_vs_tesla: {
    id: "armored_vs_tesla",
    enemyType: "armored",
    triggeredByTower: "tesla",
    name: "Insulated Tanks",
    icon: "⚡",
    desc: "Tanks immune to Tesla chain — must be targeted directly",
    apply: { immunities: ["tesla"] },
  },
  armored_vs_sniper: {
    id: "armored_vs_sniper",
    enemyType: "armored",
    triggeredByTower: "sniper",
    name: "Reactive Armor",
    icon: "🔰",
    desc: "Tanks gain +0.25 armor — armor-pierce reduced 50%",
    apply: { armorBonus: 0.25, piercingResist: 0.5 },
  },
  swarm_vs_cannon: {
    id: "swarm_vs_cannon",
    enemyType: "swarm",
    triggeredByTower: "cannon",
    name: "Dispersed Swarm",
    icon: "🌪️",
    desc: "Swarms split apart on splash — spread over wider area",
    apply: { scatterFormation: true, speedMult: 1.2 },
  },
  swarm_vs_laser: {
    id: "swarm_vs_laser",
    enemyType: "swarm",
    triggeredByTower: "laser",
    name: "Hardened Carapace",
    icon: "🪲",
    desc: "Swarms gain +60% HP",
    apply: { hpMult: 1.6 },
  },
  stealth_vs_laser: {
    id: "stealth_vs_laser",
    enemyType: "stealth",
    triggeredByTower: "laser",
    name: "Phase Cycling",
    icon: "👾",
    desc: "Ghosts phase in and out every 4 seconds — laser loses lock",
    apply: { phaseCycle: 240 },
  },
  stealth_vs_tesla: {
    id: "stealth_vs_tesla",
    enemyType: "stealth",
    triggeredByTower: "tesla",
    name: "Static Cloak",
    icon: "🌑",
    desc: "Ghosts absorb tesla chains — stealth persists after hit",
    apply: { immunities: ["tesla"] },
  },
  spread_vs_cannon: {
    id: "spread_vs_cannon",
    enemyType: "spread",
    triggeredByTower: "cannon",
    name: "Armored Brood",
    icon: "🌸",
    desc: "Brood gains 0.35 armor — children also inherit armor",
    apply: { armorBonus: 0.35, childArmorBonus: 0.2 },
  },
  fast_vs_inferno: {
    id: "fast_vs_inferno",
    enemyType: "fast",
    triggeredByTower: "inferno",
    name: "Thermal Boost",
    icon: "🔥",
    desc: "Raiders gain +40% speed when burning — fire makes them faster!",
    apply: { burnSpeedBoost: 0.4 },
  },
  fast_vs_vortex: {
    id: "fast_vs_vortex",
    enemyType: "fast",
    triggeredByTower: "vortex",
    name: "Inertial Dampener",
    icon: "🌀",
    desc: "Raiders immune to vortex pull. +15% speed.",
    apply: { gravityImmune: true, speedMult: 1.15 },
  },
  juggernaut_vs_inferno: {
    id: "juggernaut_vs_inferno",
    enemyType: "juggernaut",
    triggeredByTower: "inferno",
    name: "Asbestos Hide",
    icon: "🧱",
    desc: "Juggernauts become immune to burn damage",
    apply: { immunities: ["inferno"] },
  },
  juggernaut_vs_sniper: {
    id: "juggernaut_vs_sniper",
    enemyType: "juggernaut",
    triggeredByTower: "sniper",
    name: "Reactive Plating",
    icon: "⚙️",
    desc: "Juggernauts gain +0.3 armor and heal 5% HP when hit by armor-pierce",
    apply: { armorBonus: 0.3, healOnPierce: 0.05 },
  },
  chrono_vs_tesla: {
    id: "chrono_vs_tesla",
    enemyType: "chrono_raider",
    triggeredByTower: "tesla",
    name: "Charge Absorption",
    icon: "⚡",
    desc: "Chrono Raiders absorb Tesla arcs — each arc hit gives +5% speed stack",
    apply: { immunities: ["tesla"], speedMult: 1.2 },
  },
  chrono_vs_missile: {
    id: "chrono_vs_missile",
    enemyType: "chrono_raider",
    triggeredByTower: "missile",
    name: "Phase Shift",
    icon: "🌀",
    desc: "Chrono Raiders phase briefly on missile hit — 30% dodge chance",
    apply: { dodgeChance: 0.3 },
  },
};

// ─── ACHIEVEMENTS ─────────────────────────────────────────────────────────────
export const ACHIEVEMENTS = {
  first_wave: {
    id: "first_wave",
    name: "First Blood",
    icon: "🗡️",
    desc: "Complete your first wave",
  },
  no_leak: {
    id: "no_leak",
    name: "Flawless Wave",
    icon: "🛡️",
    desc: "Complete a wave with zero leaks",
  },
  boss_slayer: {
    id: "boss_slayer",
    name: "Boss Slayer",
    icon: "💀",
    desc: "Kill your first boss",
  },
  modifier_survive: {
    id: "modifier_survive",
    name: "Chaos Survivor",
    icon: "🌀",
    desc: "Survive a wave with an active modifier",
  },
  wave_25: {
    id: "wave_25",
    name: "Veteran",
    icon: "🎖️",
    desc: "Reach wave 25",
  },
  wave_50: {
    id: "wave_50",
    name: "Siege Master",
    icon: "🏆",
    desc: "Reach wave 50",
  },
  wave_100: {
    id: "wave_100",
    name: "Centurion",
    icon: "🌟",
    desc: "Reach wave 100",
  },
  wave_200: {
    id: "wave_200",
    name: "Ascendant",
    icon: "✨",
    desc: "Reach wave 200 — Ascension upgrades unlock",
  },
  wave_500: {
    id: "wave_500",
    name: "Godslayer",
    icon: "☠️",
    desc: "Reach wave 500. You are no longer human.",
    secret: true,
  },
  synergist: {
    id: "synergist",
    name: "Synergist",
    icon: "✨",
    desc: "Have 3+ active synergies at once",
  },
  perfect_run: {
    id: "perfect_run",
    name: "Untouchable",
    icon: "⭐",
    desc: "Win a level without losing a single life",
    secret: true,
  },
  gold_hoarder: {
    id: "gold_hoarder",
    name: "Gold Hoarder",
    icon: "💰",
    desc: "Accumulate 2000g at once",
  },
  mutation_slayer: {
    id: "mutation_slayer",
    name: "Mutant Slayer",
    icon: "🧬",
    desc: "Kill a mutated boss",
  },
  used_continue: {
    id: "used_continue",
    name: "Last Chance",
    icon: "❤️",
    desc: "Use a continue to survive",
  },
  max_continues: {
    id: "max_continues",
    name: "Never Give Up",
    icon: "💪",
    desc: "Use all 3 continues in a single run",
    secret: true,
  },
  ascension_unlocked: {
    id: "ascension_unlocked",
    name: "Ascended",
    icon: "🌌",
    desc: "Unlock an Ascension upgrade on any tower",
  },
};

// ─── DYNAMIC MAP GENERATOR ───────────────────────────────────────────────────
export function generateDynamicMap({ cols = 30, rows = 20 }) {
  const MARGIN = 2;
  const topMax = Math.floor(rows * 0.35);
  const bottomMin = Math.floor(rows * 0.65);
  const waypoints = [];
  let col = 0;
  let row = randomBetween(Math.floor(rows * 0.4), Math.floor(rows * 0.6));
  waypoints.push({ col: 0, row });
  let goTop = row >= rows / 2;
  while (col < cols - 1) {
    const remaining = cols - 1 - col;
    const minStep = Math.min(6, remaining);
    const maxStep = Math.min(Math.max(7, Math.floor(remaining * 0.5)), 13);
    const step = randomBetween(minStep, maxStep);
    const nextCol = Math.min(col + step, cols - 1);
    waypoints.push({ col: nextCol, row });
    col = nextCol;
    if (col >= cols - 1) break;
    const zone = goTop
      ? { min: MARGIN, max: topMax }
      : { min: bottomMin, max: rows - 1 - MARGIN };
    const nextRow = randomBetween(zone.min, zone.max);
    waypoints.push({ col, row: nextRow });
    row = nextRow;
    goTop = !goTop;
  }
  if (waypoints[waypoints.length - 1].col < cols - 1) {
    waypoints.push({ col: cols - 1, row });
  }
  return {
    name: "Procedural Gauntlet",
    description: "A dynamically generated S-route. No two runs alike.",
    unlockedAtLevel: 1,
    theme: randomMapTheme(),
    waypoints,
    mapBonus: { type: "damage", value: 0.08, label: "⚔️ +8% tower damage" },
  };
}

function randomBetween(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomMapTheme() {
  const themes = [
    {
      path: "#1e1b4b",
      bg: "#0f0e2a",
      pathBorder: "#3730a3",
      accent: "#818cf8",
    },
    {
      path: "#3f3f46",
      bg: "#18181b",
      pathBorder: "#71717a",
      accent: "#f97316",
    },
    {
      path: "#052e16",
      bg: "#03120a",
      pathBorder: "#16a34a",
      accent: "#4ade80",
    },
    {
      path: "#2e1065",
      bg: "#0f0a1f",
      pathBorder: "#7c3aed",
      accent: "#e879f9",
    },
  ];
  return themes[Math.floor(Math.random() * themes.length)];
}

export const SKINS = {
  default: {
    id: "default",
    name: "Default",
    unlocked: true,
    mapStyle: "tech",
    maps: {},
    towers: {},
    enemies: {},
  },
  neon: {
    id: "neon",
    name: "Neon City",
    unlocked: false,
    mapStyle: "neon",
    maps: {
      valley: {
        path: "#0a0a2e",
        bg: "#050510",
        pathBorder: "#00ffff",
        accent: "#ff00ff",
      },
      spiral: {
        path: "#0a0a2e",
        bg: "#050510",
        pathBorder: "#ff00ff",
        accent: "#00ffff",
      },
    },
    towers: {
      basic: { color: "#00ffff", projectileColor: "#00ffff" },
      sniper: { color: "#ff00ff", projectileColor: "#ff00ff" },
      cannon: { color: "#ffff00", projectileColor: "#ffff00" },
      laser: { color: "#ff6600", projectileColor: "#ff6600" },
      freeze: { color: "#00ff88", projectileColor: "#00ff88" },
      tesla: { color: "#ff66ff", projectileColor: "#ff66ff" },
      inferno: { color: "#ff3300", projectileColor: "#ff3300" },
      vortex: { color: "#6600ff", projectileColor: "#6600ff" },
      missile: { color: "#ff6600", projectileColor: "#ff6600" },
    },
    enemies: {
      basic: { color: "#ff0066" },
      fast: { color: "#ffff00" },
      armored: { color: "#00ffff" },
      boss_colossus: { color: "#ff0000" },
    },
  },
  medieval: {
    id: "medieval",
    name: "Medieval Siege",
    unlocked: false,
    mapStyle: "medieval",
    maps: {
      valley: {
        path: "#3d2b1f",
        bg: "#1a0f0a",
        pathBorder: "#8b6914",
        accent: "#d4a017",
      },
    },
    towers: {
      basic: { color: "#8b6914", projectileColor: "#c8a82a" },
      sniper: { color: "#5c4033", projectileColor: "#8b6914" },
      cannon: { color: "#4a3728", projectileColor: "#8b6914" },
    },
    enemies: { basic: { color: "#8b0000" }, armored: { color: "#696969" } },
  },
  jungle: {
    id: "jungle",
    name: "Jungle Ruins",
    unlocked: false,
    mapStyle: "jungle",
    maps: {
      valley: {
        path: "#14532d",
        bg: "#052e16",
        pathBorder: "#16a34a",
        accent: "#86efac",
      },
      spiral: {
        path: "#14532d",
        bg: "#052e16",
        pathBorder: "#15803d",
        accent: "#4ade80",
      },
      gauntlet: {
        path: "#166534",
        bg: "#052e16",
        pathBorder: "#16a34a",
        accent: "#86efac",
      },
      abyss: {
        path: "#14532d",
        bg: "#031a0e",
        pathBorder: "#15803d",
        accent: "#4ade80",
      },
    },
    towers: {
      basic: { color: "#86efac", projectileColor: "#86efac" },
      sniper: { color: "#4ade80", projectileColor: "#4ade80" },
      cannon: { color: "#a3e635", projectileColor: "#a3e635" },
      laser: { color: "#d9f99d", projectileColor: "#d9f99d" },
      freeze: { color: "#bfdbfe", projectileColor: "#bfdbfe" },
      tesla: { color: "#fde68a", projectileColor: "#fde68a" },
      inferno: { color: "#fb923c", projectileColor: "#fb923c" },
      vortex: { color: "#c084fc", projectileColor: "#c084fc" },
      missile: { color: "#fca5a5", projectileColor: "#fca5a5" },
    },
    enemies: {
      basic: { color: "#dc2626" },
      fast: { color: "#eab308" },
      armored: { color: "#78716c" },
    },
  },
};
