export const GRID_COLS = 30;
export const GRID_ROWS = 20;
export const CELL_SIZE = 36;

// ─── TOWER UPGRADE BRANCHES ───────────────────────────────────────────────────
// Each tower has 2 tiers, each with 2 branching paths (A or B).
// Player chooses ONE path per tier — cannot take both.
// XP (earned by damage dealt + kills) unlocks the ability to buy upgrades.
export const TOWER_UPGRADES = {
  basic: {
    passives: [
      { tier: 1, xp: 6, stat: "damage", mult: 0.12, label: "+12% dmg" },
      { tier: 2, xp: 14, stat: "range", mult: 0.08, label: "+8% range" },
      { tier: 3, xp: 25, stat: "damage", mult: 0.18, label: "+18% dmg" },
      { tier: 4, xp: 40, stat: "fireRate", mult: -0.1, label: "−10% cooldown" },
      { tier: 6, xp: 70, stat: "damage", mult: 0.22, label: "+22% dmg" },
      { tier: 7, xp: 95, stat: "range", mult: 0.12, label: "+12% range" },
      { tier: 8, xp: 130, stat: "damage", mult: 0.28, label: "+28% dmg" },
      {
        tier: 9,
        xp: 170,
        stat: "fireRate",
        mult: -0.15,
        label: "−15% cooldown",
      },
    ],
    skill5: {
      xp: 52,
      A: {
        name: "Marksman",
        desc: "+50% dmg, +15% range",
        icon: "🎯",
        cost: 60,
        statDelta: { damage: 0.5, range: 0.15 },
      },
      B: {
        name: "Gatling",
        desc: "2× fire rate",
        icon: "🌀",
        cost: 60,
        statDelta: { fireRate: -0.5 },
      },
    },
    skill10: {
      xp: 220,
      A: {
        name: "Deadeye",
        desc: "+100% dmg, armor pierce",
        icon: "💥",
        cost: 100,
        statDelta: { damage: 1.0 },
        special: "armorPiercing",
      },
      B: {
        name: "Assault",
        desc: "3× fire rate + splash 30",
        icon: "⚡",
        cost: 100,
        statDelta: { fireRate: -0.66 },
        special: "splash30",
      },
    },
    legendary50: {
      name: "Overwatch",
      desc: "Bullets chain to nearest enemy on hit.",
      icon: "🔱",
      cost: 400,
      special: "bulletChain",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Singularity",
      desc: "Every 10th bullet creates a black hole.",
      icon: "🌌",
      cost: 800,
      special: "blackHole",
      unlocksAtWave: 100,
    },
  },
  sniper: {
    passives: [
      { tier: 1, xp: 5, stat: "damage", mult: 0.15, label: "+15% dmg" },
      { tier: 2, xp: 12, stat: "range", mult: 0.12, label: "+12% range" },
      { tier: 3, xp: 22, stat: "damage", mult: 0.2, label: "+20% dmg" },
      { tier: 4, xp: 36, stat: "fireRate", mult: -0.1, label: "−10% cooldown" },
      { tier: 6, xp: 75, stat: "damage", mult: 0.28, label: "+28% dmg" },
      { tier: 7, xp: 105, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 8, xp: 140, stat: "damage", mult: 0.35, label: "+35% dmg" },
      {
        tier: 9,
        xp: 190,
        stat: "fireRate",
        mult: -0.12,
        label: "−12% cooldown",
      },
    ],
    skill5: {
      xp: 48,
      A: {
        name: "Longshot",
        desc: "+40% range, +30% dmg",
        icon: "🔭",
        cost: 90,
        statDelta: { range: 0.4, damage: 0.3 },
      },
      B: {
        name: "Piercer",
        desc: "Armor pierce + 20% dmg",
        icon: "🗡️",
        cost: 90,
        statDelta: { damage: 0.2 },
        special: "armorPiercing",
      },
    },
    skill10: {
      xp: 240,
      A: {
        name: "Rail Gun",
        desc: "+150% dmg, pass-through",
        icon: "☄️",
        cost: 150,
        statDelta: { damage: 1.5 },
        special: "pierceThrough",
      },
      B: {
        name: "Quantum",
        desc: "Ignores stealth + armor",
        icon: "🌌",
        cost: 150,
        statDelta: { damage: 0.5 },
        special: "fullPierce",
      },
    },
    legendary50: {
      name: "God's Eye",
      desc: "Reveals all stealth. Crits ignore armor.",
      icon: "👁️",
      cost: 400,
      special: "allReveal",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Antimatter",
      desc: "Shots trigger a delayed void explosion.",
      icon: "💫",
      cost: 800,
      special: "voidBurst",
      unlocksAtWave: 100,
    },
  },
  cannon: {
    passives: [
      { tier: 1, xp: 7, stat: "damage", mult: 0.12, label: "+12% dmg" },
      { tier: 2, xp: 16, stat: "splash", mult: 0.1, label: "+10% splash" },
      { tier: 3, xp: 28, stat: "damage", mult: 0.18, label: "+18% dmg" },
      { tier: 4, xp: 45, stat: "fireRate", mult: -0.1, label: "−10% cooldown" },
      { tier: 6, xp: 80, stat: "damage", mult: 0.22, label: "+22% dmg" },
      { tier: 7, xp: 110, stat: "splash", mult: 0.2, label: "+20% splash" },
      { tier: 8, xp: 150, stat: "damage", mult: 0.3, label: "+30% dmg" },
      {
        tier: 9,
        xp: 200,
        stat: "fireRate",
        mult: -0.15,
        label: "−15% cooldown",
      },
    ],
    skill5: {
      xp: 58,
      A: {
        name: "Bombard",
        desc: "+60% splash radius",
        icon: "💣",
        cost: 80,
        statDelta: { splash: 0.6 },
      },
      B: {
        name: "Velocity",
        desc: "+50% proj speed, −20% cd",
        icon: "🚀",
        cost: 80,
        statDelta: { projectileSpeed: 0.5, fireRate: -0.2 },
      },
    },
    skill10: {
      xp: 250,
      A: {
        name: "Napalm",
        desc: "Splash leaves burning ground",
        icon: "🔥",
        cost: 130,
        statDelta: { splash: 0.3 },
        special: "burnOnSplash",
      },
      B: {
        name: "Cluster",
        desc: "Splits into 3 mini-shots",
        icon: "🌟",
        cost: 130,
        statDelta: { damage: 0.5 },
        special: "clusterShot",
      },
    },
    legendary50: {
      name: "Earthquake",
      desc: "Every shot stuns nearby enemies 0.5s.",
      icon: "🌋",
      cost: 400,
      special: "quakeStun",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Nuke",
      desc: "Every 8th shot = full-screen nuke.",
      icon: "☢️",
      cost: 800,
      special: "nuke",
      unlocksAtWave: 100,
    },
  },
  laser: {
    passives: [
      { tier: 1, xp: 9, stat: "damage", mult: 0.12, label: "+12% dmg" },
      { tier: 2, xp: 20, stat: "range", mult: 0.1, label: "+10% range" },
      { tier: 3, xp: 35, stat: "damage", mult: 0.18, label: "+18% dmg" },
      {
        tier: 4,
        xp: 55,
        stat: "fireRate",
        mult: -0.12,
        label: "−12% cooldown",
      },
      { tier: 6, xp: 100, stat: "damage", mult: 0.25, label: "+25% dmg" },
      { tier: 7, xp: 135, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 8, xp: 180, stat: "damage", mult: 0.32, label: "+32% dmg" },
      {
        tier: 9,
        xp: 230,
        stat: "fireRate",
        mult: -0.15,
        label: "−15% cooldown",
      },
    ],
    skill5: {
      xp: 70,
      A: {
        name: "Overclock",
        desc: "2× fire rate, +20% dmg",
        icon: "⚡",
        cost: 100,
        statDelta: { fireRate: -0.5, damage: 0.2 },
      },
      B: {
        name: "Lens",
        desc: "+50% range, +30% dmg",
        icon: "🔬",
        cost: 100,
        statDelta: { range: 0.5, damage: 0.3 },
      },
    },
    skill10: {
      xp: 280,
      A: {
        name: "Death Ray",
        desc: "Hits ALL enemies in range",
        icon: "🌈",
        cost: 180,
        statDelta: { damage: 0.5 },
        special: "beamAll",
      },
      B: {
        name: "Disruptor",
        desc: "Slows + stuns 0.5s on hit",
        icon: "🌀",
        cost: 180,
        statDelta: { damage: 0.3 },
        special: "stunOnHit",
      },
    },
    legendary50: {
      name: "Solar Flare",
      desc: "Every 10th shot blinds all enemies 2s.",
      icon: "☀️",
      cost: 400,
      special: "solarBlind",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Omega Ray",
      desc: "Continuous beam hits entire path.",
      icon: "🔆",
      cost: 800,
      special: "omegaBeam",
      unlocksAtWave: 100,
    },
  },
  freeze: {
    passives: [
      {
        tier: 1,
        xp: 7,
        stat: "slowDuration",
        mult: 0.12,
        label: "+12% slow dur",
      },
      { tier: 2, xp: 16, stat: "damage", mult: 0.1, label: "+10% dmg" },
      {
        tier: 3,
        xp: 28,
        stat: "slowDuration",
        mult: 0.18,
        label: "+18% slow dur",
      },
      { tier: 4, xp: 45, stat: "range", mult: 0.1, label: "+10% range" },
      {
        tier: 6,
        xp: 80,
        stat: "slowDuration",
        mult: 0.22,
        label: "+22% slow dur",
      },
      { tier: 7, xp: 110, stat: "damage", mult: 0.2, label: "+20% dmg" },
      {
        tier: 8,
        xp: 150,
        stat: "slowDuration",
        mult: 0.28,
        label: "+28% slow dur",
      },
      { tier: 9, xp: 200, stat: "range", mult: 0.15, label: "+15% range" },
    ],
    skill5: {
      xp: 58,
      A: {
        name: "Deep Freeze",
        desc: "+50% slow duration",
        icon: "🧊",
        cost: 70,
        statDelta: { slowDuration: 0.5 },
      },
      B: {
        name: "Nova",
        desc: "Area slow on fire",
        icon: "❄️",
        cost: 70,
        special: "areaFreeze",
      },
    },
    skill10: {
      xp: 250,
      A: {
        name: "Absolute",
        desc: "Freeze fully stops enemy",
        icon: "💀",
        cost: 110,
        statDelta: { slowDuration: 0.5 },
        special: "fullFreeze",
      },
      B: {
        name: "Shatter",
        desc: "Frozen enemies take 2× dmg",
        icon: "💎",
        cost: 110,
        special: "shatterBuff",
      },
    },
    legendary50: {
      name: "Permafrost",
      desc: "Slowed enemies also lose 30% armor.",
      icon: "🌨️",
      cost: 400,
      special: "armorSlow",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Ice Age",
      desc: "On kill, freeze all nearby enemies 3s.",
      icon: "🏔️",
      cost: 800,
      special: "iceAge",
      unlocksAtWave: 100,
    },
  },
  tesla: {
    // Passive tiers — auto-applied on XP, no gold
    passives: [
      { tier: 1, xp: 8, stat: "damage", mult: 0.15, label: "+15% dmg" },
      { tier: 2, xp: 18, stat: "range", mult: 0.1, label: "+10% range" },
      { tier: 3, xp: 32, stat: "damage", mult: 0.2, label: "+20% dmg" },
      {
        tier: 4,
        xp: 50,
        stat: "fireRate",
        mult: -0.12,
        label: "−12% cooldown",
      },
      // tier 5 = skill A/B below
      { tier: 6, xp: 90, stat: "damage", mult: 0.25, label: "+25% dmg" },
      { tier: 7, xp: 120, stat: "chainTargets", flat: 1, label: "+1 chain" },
      { tier: 8, xp: 160, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 9, xp: 210, stat: "damage", mult: 0.3, label: "+30% dmg" },
      // tier 10 = skill A/B below
    ],
    // Active skill tiers — require gold, player chooses A or B
    skill5: {
      xp: 65,
      A: {
        name: "Conductor",
        desc: "+2 chain targets",
        icon: "🌩️",
        cost: 110,
        statDelta: { chainTargets: 2 },
      },
      B: {
        name: "Surge",
        desc: "+80% damage per arc",
        icon: "⚡",
        cost: 110,
        statDelta: { damage: 0.8 },
      },
    },
    skill10: {
      xp: 260,
      A: {
        name: "Storm",
        desc: "Chains to 8 targets",
        icon: "🌪️",
        cost: 160,
        statDelta: { chainTargets: 5 },
      },
      B: {
        name: "Overload",
        desc: "Chain stuns 0.3s each",
        icon: "💥",
        cost: 160,
        statDelta: { damage: 0.5 },
        special: "chainStun",
      },
    },
    // Legendary — unlocked by wave milestone, not XP
    legendary50: {
      name: "Godstorm",
      desc: "Arcs pierce boss shields. +3 chains.",
      icon: "☈",
      cost: 400,
      statDelta: { chainTargets: 3 },
      special: "shieldPierce",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Obliterator",
      desc: "Every 5th arc triggers a full-screen pulse.",
      icon: "💀",
      cost: 800,
      special: "arcPulse",
      unlocksAtWave: 100,
    },
  },
  inferno: {
    passives: [
      { tier: 1, xp: 8, stat: "burnDamage", flat: 1, label: "+1 burn/tick" },
      { tier: 2, xp: 18, stat: "range", mult: 0.1, label: "+10% range" },
      { tier: 3, xp: 32, stat: "burnDamage", flat: 2, label: "+2 burn/tick" },
      {
        tier: 4,
        xp: 50,
        stat: "burnDuration",
        mult: 0.15,
        label: "+15% burn dur",
      },
      { tier: 6, xp: 90, stat: "burnDamage", flat: 3, label: "+3 burn/tick" },
      { tier: 7, xp: 120, stat: "range", mult: 0.15, label: "+15% range" },
      { tier: 8, xp: 160, stat: "burnDamage", flat: 4, label: "+4 burn/tick" },
      {
        tier: 9,
        xp: 210,
        stat: "burnDuration",
        mult: 0.25,
        label: "+25% burn dur",
      },
    ],
    skill5: {
      xp: 65,
      A: {
        name: "Wildfire",
        desc: "+60% burn duration",
        icon: "🔥",
        cost: 120,
        statDelta: { burnDuration: 0.6 },
      },
      B: {
        name: "Floodfire",
        desc: "+40% range, area ignite",
        icon: "🌋",
        cost: 120,
        statDelta: { range: 0.4 },
        special: "areaIgnite",
      },
    },
    skill10: {
      xp: 260,
      A: {
        name: "Hellfire",
        desc: "Burn stacks 3×",
        icon: "☠️",
        cost: 180,
        statDelta: { burnDamage: 2 },
        special: "burnStack",
      },
      B: {
        name: "Meltdown",
        desc: "Burning = −40% armor",
        icon: "⚗️",
        cost: 180,
        special: "armorMelt",
      },
    },
    legendary50: {
      name: "Phoenix Core",
      desc: "Killed enemies explode, igniting neighbors.",
      icon: "🦅",
      cost: 400,
      special: "deathIgnite",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Supernova",
      desc: "Every 6th shot = massive burn AoE.",
      icon: "💢",
      cost: 800,
      special: "supernova",
      unlocksAtWave: 100,
    },
  },
  vortex: {
    passives: [
      { tier: 1, xp: 9, stat: "pullForce", flat: 0.1, label: "+0.1 pull" },
      { tier: 2, xp: 20, stat: "splash", mult: 0.1, label: "+10% splash" },
      { tier: 3, xp: 35, stat: "damage", mult: 0.18, label: "+18% dmg" },
      { tier: 4, xp: 55, stat: "pullForce", flat: 0.15, label: "+0.15 pull" },
      { tier: 6, xp: 100, stat: "damage", mult: 0.25, label: "+25% dmg" },
      { tier: 7, xp: 135, stat: "splash", mult: 0.2, label: "+20% splash" },
      { tier: 8, xp: 180, stat: "damage", mult: 0.32, label: "+32% dmg" },
      { tier: 9, xp: 230, stat: "pullForce", flat: 0.2, label: "+0.2 pull" },
    ],
    skill5: {
      xp: 70,
      A: {
        name: "Singularity",
        desc: "+50% pull, +40% splash",
        icon: "🌀",
        cost: 130,
        statDelta: { pullForce: 0.5, splash: 0.4 },
      },
      B: {
        name: "Cyclone",
        desc: "Continuous spin damage",
        icon: "🌪️",
        cost: 130,
        statDelta: { fireRate: -0.5, damage: 0.6 },
      },
    },
    skill10: {
      xp: 280,
      A: {
        name: "Void Rift",
        desc: "Teleports enemies back 20%",
        icon: "🌌",
        cost: 200,
        special: "teleportBack",
      },
      B: {
        name: "Collapse",
        desc: "Pulls + 3× damage burst",
        icon: "💥",
        cost: 200,
        statDelta: { damage: 2.0 },
      },
    },
    legendary50: {
      name: "Event Horizon",
      desc: "Enemies in range can't move at all.",
      icon: "⚫",
      cost: 400,
      special: "gravityLock",
      unlocksAtWave: 50,
    },
    legendary100: {
      name: "Big Crunch",
      desc: "Every 5th shot pulls ALL enemies on map.",
      icon: "🌑",
      cost: 800,
      special: "bigCrunch",
      unlocksAtWave: 100,
    },
  },
};

// ─── TOWERS ───────────────────────────────────────────────────────────────────
export const TOWER_TYPES = {
  basic: {
    name: "Gunner",
    cost: 50,
    damage: 22,
    range: 120,
    fireRate: 55,
    color: "#4ade80",
    projectileColor: "#4ade80",
    projectileSpeed: 5,
    icon: "🗼",
    desc: "Reliable. Balanced DPS.",
    category: "attack",
    unlockedAtLevel: 1,
    weakAgainst: ["fast", "stealth"],
    strongAgainst: ["basic", "armored"],
  },
  sniper: {
    name: "Sniper",
    cost: 100,
    damage: 90,
    range: 290,
    fireRate: 175,
    color: "#38bdf8",
    projectileColor: "#38bdf8",
    projectileSpeed: 14,
    icon: "🎯",
    desc: "Long range, high single-target.",
    category: "attack",
    unlockedAtLevel: 1,
    weakAgainst: ["swarm", "stealth"],
    strongAgainst: ["armored", "boss_colossus"],
  },
  cannon: {
    name: "Cannon",
    cost: 120,
    damage: 55,
    range: 105,
    fireRate: 120,
    color: "#f97316",
    projectileColor: "#f97316",
    projectileSpeed: 4,
    splash: 65,
    icon: "💣",
    desc: "Splash damage. Clears groups.",
    category: "attack",
    unlockedAtLevel: 1,
    weakAgainst: ["fast", "spread"],
    strongAgainst: ["swarm", "basic", "boss_titan"],
  },
  laser: {
    name: "Laser",
    cost: 150,
    damage: 9,
    range: 155,
    fireRate: 5,
    color: "#e879f9",
    projectileColor: "#e879f9",
    projectileSpeed: 22,
    icon: "⚡",
    desc: "Rapid beam. Reveals stealth.",
    category: "tech",
    unlockedAtLevel: 2,
    weakAgainst: ["armored"],
    strongAgainst: ["fast", "stealth", "boss_phantom"],
  },
  freeze: {
    name: "Cryo",
    cost: 80,
    damage: 6,
    range: 115,
    fireRate: 85,
    color: "#a5f3fc",
    projectileColor: "#a5f3fc",
    projectileSpeed: 6,
    slowFactor: 0.35,
    slowDuration: 130,
    icon: "❄️",
    desc: "Slows enemies significantly.",
    category: "support",
    unlockedAtLevel: 2,
    weakAgainst: ["armored"],
    strongAgainst: ["fast", "swarm"],
  },
  tesla: {
    name: "Tesla",
    cost: 180,
    damage: 40,
    range: 130,
    fireRate: 70,
    color: "#fbbf24",
    projectileColor: "#fbbf24",
    projectileSpeed: 18,
    chainTargets: 3,
    chainRange: 80,
    armorPiercing: true,
    icon: "🌩️",
    desc: "Chains 3 targets. Ignores armor.",
    category: "tech",
    unlockedAtLevel: 3,
    weakAgainst: ["stealth"],
    strongAgainst: ["armored", "swarm", "boss_colossus"],
  },
  inferno: {
    name: "Inferno",
    cost: 200,
    damage: 15,
    range: 100,
    fireRate: 20,
    color: "#ef4444",
    projectileColor: "#ef4444",
    projectileSpeed: 8,
    burnDamage: 5,
    burnDuration: 180,
    icon: "🔥",
    desc: "Burns enemies over time.",
    category: "attack",
    unlockedAtLevel: 4,
    weakAgainst: ["armored"],
    strongAgainst: ["fast", "swarm", "stealth", "boss_voidreaper"],
  },
  vortex: {
    name: "Vortex",
    cost: 250,
    damage: 30,
    range: 160,
    fireRate: 200,
    color: "#818cf8",
    projectileColor: "#818cf8",
    projectileSpeed: 10,
    splash: 90,
    pullForce: 0.5,
    icon: "🌀",
    desc: "Pulls & blasts all nearby.",
    category: "support",
    unlockedAtLevel: 5,
    weakAgainst: [],
    strongAgainst: ["swarm", "spread", "fast"],
  },
};

// Which towers can reveal/target stealth enemies
export const STEALTH_COUNTERS = ["laser"];

export const TOWER_CATEGORY_CAPS = {
  attack: { label: "Attack", icon: "⚔️", cap: 8 },
  support: { label: "Support", icon: "🛡️", cap: 4 },
  tech: { label: "Tech", icon: "🔬", cap: 5 },
};

// ─── ENEMIES ──────────────────────────────────────────────────────────────────
export const ENEMY_TYPES = {
  basic: {
    name: "Grunt",
    hp: 100,
    speed: 1.2,
    reward: 10,
    color: "#ef4444",
    size: 10,
    armor: 0,
    stealth: false,
    icon: "👾",
    desc: "Standard infantry.",
    immunities: [],
    counterNote: "",
  },
  fast: {
    name: "Raider",
    hp: 65,
    speed: 2.6,
    reward: 15,
    color: "#facc15",
    size: 8,
    armor: 0,
    stealth: false,
    icon: "💨",
    desc: "Extremely fast. Hard to hit.",
    immunities: [],
    counterNote: "Use Cryo to slow",
  },
  armored: {
    name: "Tank",
    hp: 320,
    speed: 0.7,
    reward: 28,
    color: "#94a3b8",
    size: 14,
    armor: 0.45,
    stealth: false,
    icon: "🛡️",
    desc: "Heavy armor. Resists non-piercing shots.",
    immunities: [],
    counterNote: "Tesla or Sniper pierces armor",
  },
  swarm: {
    name: "Swarm",
    hp: 32,
    speed: 1.9,
    reward: 5,
    color: "#fb923c",
    size: 7,
    armor: 0,
    stealth: false,
    icon: "🐝",
    desc: "Countless. Overwhelm with numbers.",
    immunities: [],
    counterNote: "Cannon splash clears groups",
  },
  stealth: {
    name: "Ghost",
    hp: 85,
    speed: 1.6,
    reward: 22,
    color: "#a78bfa",
    size: 9,
    armor: 0,
    stealth: true,
    icon: "👻",
    desc: "INVISIBLE — most towers cannot target it.",
    immunities: [],
    counterNote: "⚠ Laser ONLY can target stealth",
    requiresCounter: "laser",
  },
  spread: {
    name: "Brood",
    hp: 160,
    speed: 1.0,
    reward: 35,
    color: "#f0abfc",
    size: 12,
    armor: 0.2,
    stealth: false,
    icon: "🌸",
    desc: "Splits into 4 swarms on death.",
    immunities: [],
    counterNote: "Kill fast before it reaches end",
    spawnsOnDeath: "swarm",
    spawnCount: 4,
  },
  // ── Bosses ─────────────────────────────────────────────────────────────────
  boss_colossus: {
    name: "Colossus",
    hp: 1400,
    speed: 0.48,
    reward: 120,
    color: "#dc2626",
    size: 22,
    armor: 0.35,
    stealth: false,
    icon: "💀",
    isBoss: true,
    desc: "Armored walker. Cryo is USELESS against it.",
    immunities: ["freeze"],
    counterNote: "⚠ Cryo cannot slow it. Use Tesla (armor-pierce chains).",
    weakness: "tesla",
    weaknessHint: "Tesla chains pierce its armor and ignore Cryo-immunity.",
    phaseAt: 0.5,
    phaseBoost: { speed: 1.4, armorDelta: 0.15 },
    bossAbility: "enrage",
    lootDrop: {
      type: "speed_boost",
      duration: 600,
      label: "⚡ Speed Frenzy 10s",
    },
  },
  boss_phantom: {
    name: "Phantom Lord",
    hp: 900,
    speed: 1.1,
    reward: 150,
    color: "#7c3aed",
    size: 20,
    armor: 0.1,
    stealth: true,
    icon: "🌑",
    isBoss: true,
    desc: "Stealth wraith. Splash and bullets pass THROUGH it.",
    immunities: ["cannon", "basic"],
    counterNote: "⚠ Cannon & Gunner miss entirely. Only Laser locks on.",
    weakness: "laser",
    weaknessHint:
      "Laser auto-targets through stealth — the only tower that can hit it.",
    phaseAt: 0.4,
    phaseBoost: { speed: 0.5 },
    bossAbility: "phase",
    lootDrop: {
      type: "damage_boost",
      duration: 480,
      label: "💥 Damage Surge 8s",
    },
  },
  boss_titan: {
    name: "Titan Hive",
    hp: 2000,
    speed: 0.35,
    reward: 200,
    color: "#b45309",
    size: 26,
    armor: 0.4,
    stealth: false,
    icon: "🦂",
    isBoss: true,
    desc: "Hive-mind colossus. Tech weapons fail against its shell.",
    immunities: ["sniper", "laser"],
    counterNote: "⚠ Sniper & Laser bounce off. Use Cannon heavy splash.",
    weakness: "cannon",
    weaknessHint: "Cannon splash bypasses its tech-immunity — blast it.",
    spawnsOnDamage: { type: "swarm", every: 350, count: 3 },
    phaseAt: 0.6,
    phaseBoost: { speed: 0.2 },
    bossAbility: "spawn",
    lootDrop: { type: "gold_shower", amount: 150, label: "💰 +150g Drop" },
  },
  boss_voidreaper: {
    name: "Void Reaper",
    hp: 1600,
    speed: 0.9,
    reward: 180,
    color: "#312e81",
    size: 24,
    armor: 0.25,
    stealth: false,
    icon: "☠️",
    isBoss: true,
    desc: "Voidborn destroyer. Physical/cold damage is ABSORBED.",
    immunities: ["basic", "freeze", "cannon"],
    counterNote:
      "⚠ Gunner/Cryo/Cannon all absorbed. Inferno burns through void shields.",
    weakness: "inferno",
    weaknessHint:
      "Void energy is flammable — Inferno burn ignores its shields.",
    phaseAt: 0.45,
    phaseBoost: { speed: 0.4, armorDelta: -0.25 },
    bossAbility: "drain",
    lootDrop: { type: "lives_restore", amount: 3, label: "❤️ +3 Lives" },
  },
};

// ─── MAPS ─────────────────────────────────────────────────────────────────────
export const MAPS = {
  valley: {
    name: "Ember Valley",
    description: "Classic winding valley. Good for learning.",
    unlockedAtLevel: 1,
    theme: {
      path: "#1e293b",
      bg: "#0f172a",
      pathBorder: "#334155",
      accent: "#4ade80",
    },
    waypoints: [
      { col: 0, row: 10 },
      { col: 5, row: 10 },
      { col: 5, row: 4 },
      { col: 12, row: 4 },
      { col: 12, row: 15 },
      { col: 20, row: 15 },
      { col: 20, row: 7 },
      { col: 27, row: 7 },
      { col: 27, row: 13 },
      { col: 30, row: 13 },
    ],
  },
  spiral: {
    name: "Vortex Spiral",
    description: "Long spiral. More placement opportunities.",
    unlockedAtLevel: 2,
    theme: {
      path: "#1c1917",
      bg: "#0c0a09",
      pathBorder: "#44403c",
      accent: "#f97316",
    },
    waypoints: [
      { col: 0, row: 3 },
      { col: 26, row: 3 },
      { col: 26, row: 17 },
      { col: 4, row: 17 },
      { col: 4, row: 7 },
      { col: 20, row: 7 },
      { col: 20, row: 13 },
      { col: 8, row: 13 },
      { col: 8, row: 10 },
      { col: 30, row: 10 },
    ],
  },
  gauntlet: {
    name: "Iron Gauntlet",
    description: "Short brutal path. Expert only.",
    unlockedAtLevel: 3,
    theme: {
      path: "#1e1b4b",
      bg: "#0f0e2a",
      pathBorder: "#3730a3",
      accent: "#818cf8",
    },
    waypoints: [
      { col: 0, row: 10 },
      { col: 8, row: 10 },
      { col: 8, row: 5 },
      { col: 15, row: 5 },
      { col: 15, row: 15 },
      { col: 22, row: 15 },
      { col: 22, row: 10 },
      { col: 30, row: 10 },
    ],
  },
  abyss: {
    name: "Void Abyss",
    description: "Maximum difficulty. Chaotic long run.",
    unlockedAtLevel: 4,
    theme: {
      path: "#2d1b69",
      bg: "#0d0621",
      pathBorder: "#4c1d95",
      accent: "#e879f9",
    },
    waypoints: [
      { col: 0, row: 2 },
      { col: 28, row: 2 },
      { col: 28, row: 10 },
      { col: 2, row: 10 },
      { col: 2, row: 18 },
      { col: 30, row: 18 },
    ],
  },
};

// ─── LEVELS ───────────────────────────────────────────────────────────────────
export const LEVELS = [
  {
    id: 1,
    name: "Ember Valley",
    map: "valley",
    waves: 8,
    startGold: 300,
    startLives: 20,
    unlockedTowers: ["basic", "sniper", "cannon"],
    towerCaps: { attack: 8, support: 3, tech: 3 },
    bossWaves: { 7: "boss_colossus" },
    description: "Learn the ropes. The AI is watching.",
  },
  {
    id: 2,
    name: "Vortex Spiral",
    map: "spiral",
    waves: 10,
    startGold: 280,
    startLives: 18,
    unlockedTowers: ["basic", "sniper", "cannon", "laser", "freeze"],
    towerCaps: { attack: 7, support: 4, tech: 4 },
    bossWaves: { 8: "boss_phantom", 10: "boss_colossus" },
    description: "Two bosses. Discover their weaknesses fast.",
  },
  {
    id: 3,
    name: "Iron Gauntlet",
    map: "gauntlet",
    waves: 12,
    startGold: 260,
    startLives: 16,
    unlockedTowers: ["basic", "sniper", "cannon", "laser", "freeze", "tesla"],
    towerCaps: { attack: 6, support: 4, tech: 5 },
    bossWaves: { 5: "boss_colossus", 9: "boss_phantom", 12: "boss_titan" },
    description: "Three bosses. Every cap slot matters.",
  },
  {
    id: 4,
    name: "Void Abyss",
    map: "abyss",
    waves: 14,
    startGold: 240,
    startLives: 14,
    unlockedTowers: [
      "basic",
      "sniper",
      "cannon",
      "laser",
      "freeze",
      "tesla",
      "inferno",
    ],
    towerCaps: { attack: 6, support: 3, tech: 5 },
    bossWaves: {
      4: "boss_phantom",
      8: "boss_titan",
      11: "boss_voidreaper",
      14: "boss_colossus",
    },
    description: "Tight caps, brutal bosses. Every decision is critical.",
  },
  {
    id: 5,
    name: "Final Crucible",
    map: "abyss",
    waves: 16,
    startGold: 220,
    startLives: 12,
    unlockedTowers: [
      "basic",
      "sniper",
      "cannon",
      "laser",
      "freeze",
      "tesla",
      "inferno",
      "vortex",
    ],
    towerCaps: { attack: 5, support: 3, tech: 5 },
    bossWaves: {
      4: "boss_colossus",
      8: "boss_phantom",
      11: "boss_titan",
      14: "boss_voidreaper",
      16: "boss_titan",
    },
    description: "Full arsenal. Max AI aggression. Survive if you can.",
  },
];

// ─── ENDLESS MODE ─────────────────────────────────────────────────────────────
// Uses all maps rotating, all towers, scaling difficulty every 10 waves.
export const ENDLESS_CONFIG = {
  id: 99,
  name: "Endless Siege",
  isEndless: true,
  startGold: 350,
  startLives: 25,
  unlockedTowers: Object.keys({
    basic: 1,
    sniper: 1,
    cannon: 1,
    laser: 1,
    freeze: 1,
    tesla: 1,
    inferno: 1,
    vortex: 1,
  }),
  towerCaps: { attack: 10, support: 6, tech: 7 },
  waves: Infinity,
  bossWaves: {},
  // Milestone mechanics that unlock every 10 waves
  mechanics: {
    10: { label: "Elite Units", desc: "Enemies gain 20% armor permanently" },
    20: { label: "Speed Surge", desc: "All enemies permanently +15% faster" },
    30: { label: "Boss Escort", desc: "Bosses now arrive with armored guard" },
    40: { label: "Void Rifts", desc: "Stealth enemies appear in all waves" },
    50: { label: "Titan Protocol", desc: "Boss HP x2, double boss waves" },
  },
  // Boss rotation every 5 waves from wave 10 — used by WaveAI._endlessBossForWave
  bossSchedule: [
    "boss_colossus",
    "boss_phantom",
    "boss_titan",
    "boss_voidreaper",
  ],
};

// ─── ABILITIES ────────────────────────────────────────────────────────────────
export const ABILITIES = {
  airstrike: {
    name: "Airstrike",
    icon: "✈️",
    desc: "Deals 500 damage to all enemies on screen",
    cooldown: 900,
    cost: 0,
    color: "#ef4444",
  },
  emp: {
    name: "EMP Blast",
    icon: "🌐",
    desc: "Stuns all enemies for 3 seconds",
    cooldown: 720,
    cost: 0,
    color: "#fbbf24",
  },
  reinforce: {
    name: "Reinforce",
    icon: "🏰",
    desc: "All towers fire 2× faster for 8 seconds",
    cooldown: 1200,
    cost: 0,
    color: "#4ade80",
  },
};

// ─── SYNERGY BONUSES ──────────────────────────────────────────────────────────
export const SYNERGIES = {
  freeze_cannon: {
    towers: ["freeze", "cannon"],
    name: "Shatter",
    desc: "Slowed enemies take +50% splash damage",
    color: "#a5f3fc",
    bonus: { splashDamageVsSlowed: 0.5 },
  },
  laser_tesla: {
    towers: ["laser", "tesla"],
    name: "Overcharge",
    desc: "Tesla chains to laser-revealed stealth targets",
    color: "#fbbf24",
    bonus: { teslaRevealStealth: true },
  },
  inferno_cannon: {
    towers: ["inferno", "cannon"],
    name: "Napalm Zone",
    desc: "Cannon splash leaves burning ground for 3s",
    color: "#ef4444",
    bonus: { burnGround: true },
  },
  sniper_freeze: {
    towers: ["sniper", "freeze"],
    name: "Frozen Target",
    desc: "Sniper crits on slowed enemies (+80% dmg)",
    color: "#38bdf8",
    bonus: { sniperCritOnSlowed: 0.8 },
  },
};

// ─── ADMIN CONFIG ─────────────────────────────────────────────────────────────
export const ADMIN_CONFIG = {
  ai: {
    learningRate: 0.15,
    minWavesBeforeAdapt: 2,
    crossGameMemoryDecay: 0.82,
    maxExploitAttempts: 4,
    bossHpScaling: 2.0,
    enemyHpPerWave: 0.13,
    enemySpeedPerWave: 0.02,
    endlessHpPerWave: 0.1,
    endlessSpeedPerWave: 0.015,
  },
  economy: {
    waveClearBonus: 20,
    waveClearBonusPerWave: 5,
    towerSellRatio: 0.6,
  },
  visual: {
    showBossImmunityHints: true,
    bossWarningFrames: 200,
  },
};

export const STARTING_GOLD = 300;
export const STARTING_LIVES = 20;
